.TH "BLACS/TESTING Directory Reference" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/TESTING Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBblacstest\&.f\fP"
.br
.ti -1c
.RI "file \fBbtprim\&.f\fP"
.br
.ti -1c
.RI "file \fBCbt\&.c\fP"
.br
.ti -1c
.RI "file \fBCbt\&.h\fP"
.br
.ti -1c
.RI "file \fBtools\&.f\fP"
.br
.in -1c
