.TH "PBLAS/TESTING Directory Reference" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/TESTING Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdlamch\&.f\fP"
.br
.ti -1c
.RI "file \fBPB_Cabort\&.c\fP"
.br
.ti -1c
.RI "file \fBPB_Cwarn\&.c\fP"
.br
.ti -1c
.RI "file \fBpblastst\&.f\fP"
.br
.ti -1c
.RI "file \fBpcblas1tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpcblas2tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpcblas3tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpcblastst\&.f\fP"
.br
.ti -1c
.RI "file \fBpdblas1tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpdblas2tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpdblas3tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpdblastst\&.f\fP"
.br
.ti -1c
.RI "file \fBpsblas1tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpsblas2tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpsblas3tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpsblastst\&.f\fP"
.br
.ti -1c
.RI "file \fBpzblas1tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpzblas2tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpzblas3tst\&.f\fP"
.br
.ti -1c
.RI "file \fBpzblastst\&.f\fP"
.br
.ti -1c
.RI "file \fBslamch\&.f\fP"
.br
.in -1c
