.TH "PBLAS/SRC Directory Reference" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBPBBLAS\fP"
.br
.ti -1c
.RI "directory \fBPTOOLS\fP"
.br
.ti -1c
.RI "directory \fBPTZBLAS\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPBblacs\&.h\fP"
.br
.ti -1c
.RI "file \fBPBblas\&.h\fP"
.br
.ti -1c
.RI "file \fBpblas\&.h\fP"
.br
.ti -1c
.RI "file \fBPBpblas\&.h\fP"
.br
.ti -1c
.RI "file \fBPBtools\&.h\fP"
.br
.ti -1c
.RI "file \fBpcagemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcahemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcamax_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcatrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcaxpy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpccopy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcdotc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcdotu_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcgeadd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcgemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcgemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcgerc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcgeru_\&.c\fP"
.br
.ti -1c
.RI "file \fBpchemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpchemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcher2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcher2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcher_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcherk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcsscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcswap_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcsymm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcsyr2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpcsyrk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctradd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctranc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctranu_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctrmm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctrsm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpctrsv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdagemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdamax_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdasum_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdasymv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdatrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdaxpy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdcopy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpddot_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdgeadd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdgemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdgemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdger_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdnrm2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdswap_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsymm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsymv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsyr2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsyr2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsyr_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdsyrk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtradd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtran_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtrmm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtrsm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtrsv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdzasum_\&.c\fP"
.br
.ti -1c
.RI "file \fBpdznrm2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpicopy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpilaenv\&.f\fP"
.br
.ti -1c
.RI "file \fBpsagemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsamax_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsasum_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsasymv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsatrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsaxpy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpscasum_\&.c\fP"
.br
.ti -1c
.RI "file \fBpscnrm2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpscopy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsdot_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsgeadd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsgemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsgemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsger_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsnrm2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpsswap_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssymm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssymv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssyr2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssyr2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssyr_\&.c\fP"
.br
.ti -1c
.RI "file \fBpssyrk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstradd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstran_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstrmm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstrsm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpstrsv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzagemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzahemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzamax_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzatrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzaxpy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzcopy_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzdotc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzdotu_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzdscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgeadd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgerc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgeru_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzhemm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzhemv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzher2_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzher2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzher_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzherk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzscal_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzswap_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzsymm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzsyr2k_\&.c\fP"
.br
.ti -1c
.RI "file \fBpzsyrk_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztradd_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztranc_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztranu_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztrmm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztrmv_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztrsm_\&.c\fP"
.br
.ti -1c
.RI "file \fBpztrsv_\&.c\fP"
.br
.in -1c
