.TH "REDIST/TESTING Directory Reference" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
REDIST/TESTING Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpcgemrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpctrmrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpdgemrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpdtrmrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpigemrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpitrmrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpsgemrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpstrmrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpzgemrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBpztrmrdrv\&.c\fP"
.br
.ti -1c
.RI "file \fBredist\&.h\fP"
.br
.in -1c
