.TH "BLACS/SRC/BI_Arecv.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/BI_Arecv.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBI_Arecv\fP (\fBBLACSCONTEXT\fP *ctxt, int src, int msgid, \fBBLACBUFF\fP *bp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BI_Arecv (\fBBLACSCONTEXT\fP * ctxt, int src, int msgid, \fBBLACBUFF\fP * bp)"

.PP
Definition at line 3 of file BI_Arecv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
