.TH "BLACS/SRC/BI_ContxtNum.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/BI_ContxtNum.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBI_ContxtNum\fP (\fBBLACSCONTEXT\fP *ctxt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int BI_ContxtNum (\fBBLACSCONTEXT\fP * ctxt)"

.PP
Definition at line 3 of file BI_ContxtNum\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
