.TH "BLACS/SRC/BI_HypBS.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/BI_HypBS.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBI_HypBS\fP (\fBBLACSCONTEXT\fP *ctxt, \fBBLACBUFF\fP *bp, \fBSDRVPTR\fP send)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int BI_HypBS (\fBBLACSCONTEXT\fP * ctxt, \fBBLACBUFF\fP * bp, \fBSDRVPTR\fP send)"

.PP
Definition at line 2 of file BI_HypBS\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
