.TH "BLACS/SRC/BI_IdringBR.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/BI_IdringBR.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBI_IdringBR\fP (\fBBLACSCONTEXT\fP *ctxt, \fBBLACBUFF\fP *bp, \fBSDRVPTR\fP send, int src, int step)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BI_IdringBR (\fBBLACSCONTEXT\fP * ctxt, \fBBLACBUFF\fP * bp, \fBSDRVPTR\fP send, int src, int step)"

.PP
Definition at line 3 of file BI_IdringBR\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
