.TH "BLACS/SRC/BI_imvcopy.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/BI_imvcopy.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBI_imvcopy\fP (int m, int n, int *A, int lda, int *buff)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BI_imvcopy (int m, int n, int * A, int lda, int * buff)"

.PP
Definition at line 2 of file BI_imvcopy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
