.TH "bLaCsCoNtExT" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bLaCsCoNtExT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bdef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBLACSSCOPE\fP \fBrscp\fP"
.br
.ti -1c
.RI "\fBBLACSSCOPE\fP \fBcscp\fP"
.br
.ti -1c
.RI "\fBBLACSSCOPE\fP \fBascp\fP"
.br
.ti -1c
.RI "\fBBLACSSCOPE\fP \fBpscp\fP"
.br
.ti -1c
.RI "\fBBLACSSCOPE\fP * \fBscp\fP"
.br
.ti -1c
.RI "int \fBTopsRepeat\fP"
.br
.ti -1c
.RI "int \fBTopsCohrnt\fP"
.br
.ti -1c
.RI "int \fBNb_bs\fP"
.br
.ti -1c
.RI "int \fBNr_bs\fP"
.br
.ti -1c
.RI "int \fBNb_co\fP"
.br
.ti -1c
.RI "int \fBNr_co\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file Bdef\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBLACSSCOPE\fP bLaCsCoNtExT::ascp"

.PP
Definition at line 25 of file Bdef\&.h\&.
.SS "\fBBLACSSCOPE\fP bLaCsCoNtExT::cscp"

.PP
Definition at line 25 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::Nb_bs"

.PP
Definition at line 29 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::Nb_co"

.PP
Definition at line 30 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::Nr_bs"

.PP
Definition at line 29 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::Nr_co"

.PP
Definition at line 30 of file Bdef\&.h\&.
.SS "\fBBLACSSCOPE\fP bLaCsCoNtExT::pscp"

.PP
Definition at line 25 of file Bdef\&.h\&.
.SS "\fBBLACSSCOPE\fP bLaCsCoNtExT::rscp"

.PP
Definition at line 25 of file Bdef\&.h\&.
.SS "\fBBLACSSCOPE\fP* bLaCsCoNtExT::scp"

.PP
Definition at line 26 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::TopsCohrnt"

.PP
Definition at line 28 of file Bdef\&.h\&.
.SS "int bLaCsCoNtExT::TopsRepeat"

.PP
Definition at line 27 of file Bdef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
