.TH "BLACS/SRC/blacs_info_.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/blacs_info_.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBF_VOID_FUNC\fP \fBblacs_gridinfo_\fP (int *ConTxt, int *nprow, int *npcol, int *myrow, int *mycol)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBF_VOID_FUNC\fP blacs_gridinfo_ (int * ConTxt, int * nprow, int * npcol, int * myrow, int * mycol)"

.PP
Definition at line 6 of file blacs_info_\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
