.TH "bLaCsScOpE" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bLaCsScOpE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bdef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "MPI_Comm \fBcomm\fP"
.br
.ti -1c
.RI "int \fBScpId\fP"
.br
.ti -1c
.RI "int \fBMaxId\fP"
.br
.ti -1c
.RI "int \fBMinId\fP"
.br
.ti -1c
.RI "int \fBNp\fP"
.br
.ti -1c
.RI "int \fBIam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Bdef\&.h\&.
.SH "Field Documentation"
.PP 
.SS "MPI_Comm bLaCsScOpE::comm"

.PP
Definition at line 15 of file Bdef\&.h\&.
.SS "int bLaCsScOpE::Iam"

.PP
Definition at line 17 of file Bdef\&.h\&.
.SS "int bLaCsScOpE::MaxId"

.PP
Definition at line 16 of file Bdef\&.h\&.
.SS "int bLaCsScOpE::MinId"

.PP
Definition at line 16 of file Bdef\&.h\&.
.SS "int bLaCsScOpE::Np"

.PP
Definition at line 17 of file Bdef\&.h\&.
.SS "int bLaCsScOpE::ScpId"

.PP
Definition at line 16 of file Bdef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
