.TH "TOOLS/ccdotu.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/ccdotu.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBccdotu\fP (N, DOTU, X, INCX, Y, INCY)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ccdotu (integer N, \fBcomplex\fP DOTU, \fBcomplex\fP, dimension( * ) X, integer INCX, \fBcomplex\fP, dimension( * ) Y, integer INCY)"

.PP
Definition at line 2 of file ccdotu\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
