.TH "SRC/clamsh.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/clamsh.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBclamsh\fP (S, LDS, NBULGE, JBLK, H, LDH, N, ULP)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine clamsh (\fBcomplex\fP, dimension( lds, * ) S, integer LDS, integer NBULGE, integer JBLK, \fBcomplex\fP, dimension( ldh, * ) H, integer LDH, integer N, real ULP)"

.PP
Definition at line 2 of file clamsh\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
