.TH "SRC/claref.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/claref.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBclaref\fP (\fBTYPE\fP, A, LDA, WANTZ, Z, LDZ, BLOCK, IROW1, ICOL1, ISTART, ISTOP, ITMP1, ITMP2, LILOZ, LIHIZ, VECS, V2, V3, T1, T2, T3)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine claref (character TYPE, \fBcomplex\fP, dimension( lda, * ) A, integer LDA, logical WANTZ, \fBcomplex\fP, dimension( ldz, * ) Z, integer LDZ, logical BLOCK, integer IROW1, integer ICOL1, integer ISTART, integer ISTOP, integer ITMP1, integer ITMP2, integer LILOZ, integer LIHIZ, \fBcomplex\fP, dimension( * ) VECS, \fBcomplex\fP V2, \fBcomplex\fP V3, \fBcomplex\fP T1, \fBcomplex\fP T2, \fBcomplex\fP T3)"

.PP
Definition at line 4 of file claref\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
