.TH "PBLAS/SRC/PTZBLAS/cmmadd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/cmmadd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcmmadd\fP (M, N, ALPHA, A, LDA, BETA, B, LDB)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine cmmadd (integer M, integer N, \fBcomplex\fP ALPHA, \fBcomplex\fP, dimension( lda, * ) A, integer LDA, \fBcomplex\fP BETA, \fBcomplex\fP, dimension( ldb, * ) B, integer LDB)"

.PP
Definition at line 2 of file cmmadd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
