.TH "complex16" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex16
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pblas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBre\fP"
.br
.ti -1c
.RI "double \fBim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file pblas\&.h\&.
.SH "Field Documentation"
.PP 
.SS "double complex16::im"

.PP
Definition at line 93 of file pblas\&.h\&.
.SS "double complex16::re"

.PP
Definition at line 93 of file pblas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
