.TH "complex" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pblas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBi\fP"
.br
.ti -1c
.RI "float \fBre\fP"
.br
.ti -1c
.RI "float \fBim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file pcgemr\&.c\&.
.SH "Field Documentation"
.PP 
.SS "float complex::i"

.PP
Definition at line 161 of file pcgemr\&.c\&.
.SS "float complex::im"

.PP
Definition at line 92 of file pblas\&.h\&.
.SS "float complex::r"

.PP
Definition at line 161 of file pcgemr\&.c\&.
.SS "float complex::re"

.PP
Definition at line 92 of file pblas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
