.TH "SRC/csteqr2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/csteqr2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcsteqr2\fP (COMPZ, N, D, E, Z, LDZ, NR, WORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine csteqr2 (character COMPZ, integer N, real, dimension( * ) D, real, dimension( * ) E, \fBcomplex\fP, dimension( ldz, * ) Z, integer LDZ, integer NR, real, dimension( * ) WORK, integer INFO)"

.PP
Definition at line 2 of file csteqr2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
