.TH "SRC/ddttrf.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/ddttrf.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBddttrf\fP (N, DL, D, DU, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ddttrf (integer N, double precision, dimension( * ) DL, double precision, dimension( * ) D, double precision, dimension( * ) DU, integer INFO)"

.PP
Definition at line 2 of file ddttrf\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
