.TH "TOOLS/descinit.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/descinit.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdescinit\fP (DESC, M, N, MB, NB, IRSRC, ICSRC, ICTXT, LLD, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine descinit (integer, dimension( * ) DESC, integer M, integer N, integer MB, integer NB, integer IRSRC, integer ICSRC, integer ICTXT, integer LLD, integer INFO)"

.PP
Definition at line 3 of file descinit\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
