.TH "PBLAS/TESTING/dlamch.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/TESTING/dlamch.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "double precision function \fBdlamch\fP (CMACH)"
.br
.ti -1c
.RI "subroutine \fBdlamc1\fP (BETA, T, RND, IEEE1)"
.br
.ti -1c
.RI "subroutine \fBdlamc2\fP (BETA, T, RND, EPS, EMIN, RMIN, EMAX, RMAX)"
.br
.ti -1c
.RI "double precision function \fBdlamc3\fP (A, B)"
.br
.ti -1c
.RI "subroutine \fBdlamc4\fP (EMIN, START, BASE)"
.br
.ti -1c
.RI "subroutine \fBdlamc5\fP (BETA, P, EMIN, IEEE, EMAX, RMAX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dlamc1 (integer BETA, integer T, logical RND, logical IEEE1)"

.PP
Definition at line 132 of file dlamch\&.f\&.
.SS "subroutine dlamc2 (integer BETA, integer T, logical RND, double precision EPS, integer EMIN, double precision RMIN, integer EMAX, double precision RMAX)"

.PP
Definition at line 319 of file dlamch\&.f\&.
.SS "double precision function dlamc3 (double precision A, double precision B)"

.PP
Definition at line 578 of file dlamch\&.f\&.
.SS "subroutine dlamc4 (integer EMIN, double precision START, integer BASE)"

.PP
Definition at line 616 of file dlamch\&.f\&.
.SS "subroutine dlamc5 (integer BETA, integer P, integer EMIN, logical IEEE, integer EMAX, double precision RMAX)"

.PP
Definition at line 700 of file dlamch\&.f\&.
.SS "double precision function dlamch (character CMACH)"

.PP
Definition at line 2 of file dlamch\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
