.TH "SRC/dlamov.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/dlamov.c
.SH SYNOPSIS
.br
.PP
\fC#include 'lamov\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTYPE\fP   double"
.br
.ti -1c
.RI "#define \fBFUNC\fP   'DLAMOV'"
.br
.ti -1c
.RI "#define \fBLAMOV\fP   dlamov_"
.br
.ti -1c
.RI "#define \fBLACPY\fP   \fBdlacpy_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FUNC   'DLAMOV'"

.PP
Definition at line 8 of file dlamov\&.c\&.
.SS "#define LACPY   \fBdlacpy_\fP"

.PP
Definition at line 10 of file dlamov\&.c\&.
.SS "#define LAMOV   dlamov_"

.PP
Definition at line 9 of file dlamov\&.c\&.
.SS "#define TYPE   double"

.PP
Definition at line 7 of file dlamov\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
