.TH "TOOLS/dscnrm2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/dscnrm2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "double precision function \fBdscnrm2\fP (N, X, INCX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "double precision function dscnrm2 (integer N, \fBcomplex\fP, dimension( * ) X, integer INCX)"

.PP
Definition at line 2 of file dscnrm2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
