.TH "PBLAS/SRC/PTZBLAS/dset.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/dset.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdset\fP (N, ALPHA, X, INCX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dset (integer N, double precision ALPHA, double precision, dimension( * ) X, integer INCX)"

.PP
Definition at line 2 of file dset\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
