.TH "SRC/dtrmvt.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/dtrmvt.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdtrmvt\fP (UPLO, N, T, LDT, X, INCX, Y, INCY, W, INCW, Z, INCZ)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dtrmvt (character UPLO, integer N, double precision, dimension( ldt, * ) T, integer LDT, double precision, dimension( * ) X, integer INCX, double precision, dimension( * ) Y, integer INCY, double precision, dimension( * ) W, integer INCW, double precision, dimension( * ) Z, integer INCZ)"

.PP
Definition at line 3 of file dtrmvt\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
