.TH "PBLAS/SRC/PTZBLAS/dzvasum.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/dzvasum.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdzvasum\fP (N, ASUM, X, INCX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dzvasum (integer N, double precision ASUM, \fBcomplex\fP*16, dimension( * ) X, integer INCX)"

.PP
Definition at line 2 of file dzvasum\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
