.TH "BLACS/SRC/free_handle_.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/SRC/free_handle_.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Bdef\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_blacs_system_handle_\fP (int *ISysCxt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_blacs_system_handle_ (int * ISysCxt)"

.PP
Definition at line 6 of file free_handle_\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
