.TH "IDESC" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDESC
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlstart\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBgstart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 175 of file pcgemr\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int IDESC::gstart"

.PP
Definition at line 191 of file pctrmr\&.c\&.
.SS "int IDESC::len"

.PP
Definition at line 177 of file pcgemr\&.c\&.
.SS "int IDESC::lstart"

.PP
Definition at line 176 of file pcgemr\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
