.TH "PBLAS/SRC/PTZBLAS/immdda.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/immdda.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBimmdda\fP (M, N, ALPHA, A, LDA, BETA, B, LDB)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine immdda (integer M, integer N, integer ALPHA, integer, dimension( lda, * ) A, integer LDA, integer BETA, integer, dimension( ldb, * ) B, integer LDB)"

.PP
Definition at line 2 of file immdda\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
