.TH "TOOLS/indxg2p.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/indxg2p.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBindxg2p\fP (INDXGLOB, NB, IPROC, ISRCPROC, NPROCS)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function indxg2p (integer INDXGLOB, integer NB, integer IPROC, integer ISRCPROC, integer NPROCS)"

.PP
Definition at line 2 of file indxg2p\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
