.TH "MDESC" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MDESC
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdesctype\fP"
.br
.ti -1c
.RI "int \fBctxt\fP"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBnbrow\fP"
.br
.ti -1c
.RI "int \fBnbcol\fP"
.br
.ti -1c
.RI "int \fBsprow\fP"
.br
.ti -1c
.RI "int \fBspcol\fP"
.br
.ti -1c
.RI "int \fBlda\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file pcgemr\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int MDESC::ctxt"

.PP
Definition at line 165 of file pcgemr\&.c\&.
.SS "int MDESC::desctype"

.PP
Definition at line 164 of file pcgemr\&.c\&.
.SS "int MDESC::lda"

.PP
Definition at line 172 of file pcgemr\&.c\&.
.SS "int MDESC::m"

.PP
Definition at line 166 of file pcgemr\&.c\&.
.SS "int MDESC::n"

.PP
Definition at line 167 of file pcgemr\&.c\&.
.SS "int MDESC::nbcol"

.PP
Definition at line 169 of file pcgemr\&.c\&.
.SS "int MDESC::nbrow"

.PP
Definition at line 168 of file pcgemr\&.c\&.
.SS "int MDESC::spcol"

.PP
Definition at line 171 of file pcgemr\&.c\&.
.SS "int MDESC::sprow"

.PP
Definition at line 170 of file pcgemr\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
