.TH "PBLAS/SRC/PTOOLS/PB_Ctztrmv.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTOOLS/PB_Ctztrmv.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./pblas\&.h'\fP
.br
\fC#include '\&.\&./PBpblas\&.h'\fP
.br
\fC#include '\&.\&./PBtools\&.h'\fP
.br
\fC#include '\&.\&./PBblacs\&.h'\fP
.br
\fC#include '\&.\&./PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPB_Ctztrmv\fP (\fBPBTYP_T\fP *\fBTYPE\fP, char *SIDE, char *UPLO, char *TRANS, char *DIAG, int M, int N, int K, int IOFFD, char *ALPHA, char *A, int LDA, char *X, int LDX, char *Y, int LDY)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PB_Ctztrmv (\fBPBTYP_T\fP            * TYPE, char               * SIDE, char * UPLO, char * TRANS, char * DIAG, int M, int N, int K, int IOFFD, char               * ALPHA, char               * A, int LDA, char * X, int LDX, char * Y, int LDY)"

.PP
Definition at line 25 of file PB_Ctztrmv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
