.TH "PBLAS/TIMING/PB_Cabort.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/TIMING/PB_Cabort.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./pblas\&.h'\fP
.br
\fC#include '\&.\&./PBpblas\&.h'\fP
.br
\fC#include '\&.\&./PBtools\&.h'\fP
.br
\fC#include '\&.\&./PBblacs\&.h'\fP
.br
\fC#include '\&.\&./PBblas\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPB_NoAbort\fP   pb_noabort_"
.br
.ti -1c
.RI "#define \fBPB_NoAbort\fP   PB_NOABORT"
.br
.ti -1c
.RI "#define \fBPB_NoAbort\fP   \fBpb_noabort\fP"
.br
.ti -1c
.RI "#define \fBPB_NoAbort\fP   pb_noabort__"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPB_Cabort\fP (int ICTXT, char *ROUT, int INFO)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PB_NoAbort   pb_noabort_"

.PP
Definition at line 57 of file PB_Cabort\&.c\&.
.SS "#define PB_NoAbort   PB_NOABORT"

.PP
Definition at line 57 of file PB_Cabort\&.c\&.
.SS "#define PB_NoAbort   \fBpb_noabort\fP"

.PP
Definition at line 57 of file PB_Cabort\&.c\&.
.SS "#define PB_NoAbort   pb_noabort__"

.PP
Definition at line 57 of file PB_Cabort\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void PB_Cabort (int ICTXT, char           * ROUT, int INFO)"

.PP
Definition at line 63 of file PB_Cabort\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
