.TH "PBLAS/SRC/PTOOLS/PB_Cgcd.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTOOLS/PB_Cgcd.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./pblas\&.h'\fP
.br
\fC#include '\&.\&./PBpblas\&.h'\fP
.br
\fC#include '\&.\&./PBtools\&.h'\fP
.br
\fC#include '\&.\&./PBblacs\&.h'\fP
.br
\fC#include '\&.\&./PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPB_Cgcd\fP (int M, int N)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int PB_Cgcd (int M, int N)"

.PP
Definition at line 22 of file PB_Cgcd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
