.TH "PBLAS/SRC/PTOOLS/PB_Cplaprnt.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTOOLS/PB_Cplaprnt.c
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./pblas\&.h'\fP
.br
\fC#include '\&.\&./PBpblas\&.h'\fP
.br
\fC#include '\&.\&./PBtools\&.h'\fP
.br
\fC#include '\&.\&./PBblacs\&.h'\fP
.br
\fC#include '\&.\&./PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPB_Cplaprnt\fP (\fBPBTYP_T\fP *\fBTYPE\fP, int M, int N, char *A, int IA, int JA, int *DESCA, int IRPRNT, int ICPRNT, char *CMATNM)"
.br
.ti -1c
.RI "void \fBPB_Cplaprn2\fP (\fBPBTYP_T\fP *\fBTYPE\fP, int M, int N, char *A, int IA, int JA, int *DESCA, int IRPRNT, int ICPRNT, char *CMATNM, int PROW, int PCOL)"
.br
.ti -1c
.RI "void \fBPB_Cprnt\fP (int \fBTYPE\fP, int SIZE, int USIZ, int N, char *A, int IA, int JA, char *CMATNM)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PB_Cplaprn2 (\fBPBTYP_T\fP        * TYPE, int M, int N, char           * A, int IA, int JA, int            * DESCA, int IRPRNT, int ICPRNT, char * CMATNM, int PROW, int PCOL)"

.PP
Definition at line 246 of file PB_Cplaprnt\&.c\&.
.SS "void PB_Cplaprnt (\fBPBTYP_T\fP        * TYPE, int M, int N, char           * A, int IA, int JA, int            * DESCA, int IRPRNT, int ICPRNT, char * CMATNM)"

.PP
Definition at line 24 of file PB_Cplaprnt\&.c\&.
.SS "void PB_Cprnt (int TYPE, int SIZE, int USIZ, int N, char           * A, int IA, int JA, char * CMATNM)"

.PP
Definition at line 497 of file PB_Cplaprnt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
