.TH "PB_VM_T" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PB_VM_T
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pblas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoffd\fP"
.br
.ti -1c
.RI "int \fBlcmt00\fP"
.br
.ti -1c
.RI "int \fBmp\fP"
.br
.ti -1c
.RI "int \fBimb1\fP"
.br
.ti -1c
.RI "int \fBimbloc\fP"
.br
.ti -1c
.RI "int \fBmb\fP"
.br
.ti -1c
.RI "int \fBlmbloc\fP"
.br
.ti -1c
.RI "int \fBmblks\fP"
.br
.ti -1c
.RI "int \fBiupp\fP"
.br
.ti -1c
.RI "int \fBupp\fP"
.br
.ti -1c
.RI "int \fBprow\fP"
.br
.ti -1c
.RI "int \fBnprow\fP"
.br
.ti -1c
.RI "int \fBnq\fP"
.br
.ti -1c
.RI "int \fBinb1\fP"
.br
.ti -1c
.RI "int \fBinbloc\fP"
.br
.ti -1c
.RI "int \fBnb\fP"
.br
.ti -1c
.RI "int \fBlnbloc\fP"
.br
.ti -1c
.RI "int \fBnblks\fP"
.br
.ti -1c
.RI "int \fBilow\fP"
.br
.ti -1c
.RI "int \fBlow\fP"
.br
.ti -1c
.RI "int \fBpcol\fP"
.br
.ti -1c
.RI "int \fBnpcol\fP"
.br
.ti -1c
.RI "int \fBlcmb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 432 of file pblas\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int PB_VM_T::ilow"

.PP
Definition at line 454 of file pblas\&.h\&.
.SS "int PB_VM_T::imb1"

.PP
Definition at line 438 of file pblas\&.h\&.
.SS "int PB_VM_T::imbloc"

.PP
Definition at line 439 of file pblas\&.h\&.
.SS "int PB_VM_T::inb1"

.PP
Definition at line 449 of file pblas\&.h\&.
.SS "int PB_VM_T::inbloc"

.PP
Definition at line 450 of file pblas\&.h\&.
.SS "int PB_VM_T::iupp"

.PP
Definition at line 443 of file pblas\&.h\&.
.SS "int PB_VM_T::lcmb"

.PP
Definition at line 459 of file pblas\&.h\&.
.SS "int PB_VM_T::lcmt00"

.PP
Definition at line 435 of file pblas\&.h\&.
.SS "int PB_VM_T::lmbloc"

.PP
Definition at line 441 of file pblas\&.h\&.
.SS "int PB_VM_T::lnbloc"

.PP
Definition at line 452 of file pblas\&.h\&.
.SS "int PB_VM_T::low"

.PP
Definition at line 455 of file pblas\&.h\&.
.SS "int PB_VM_T::mb"

.PP
Definition at line 440 of file pblas\&.h\&.
.SS "int PB_VM_T::mblks"

.PP
Definition at line 442 of file pblas\&.h\&.
.SS "int PB_VM_T::mp"

.PP
Definition at line 437 of file pblas\&.h\&.
.SS "int PB_VM_T::nb"

.PP
Definition at line 451 of file pblas\&.h\&.
.SS "int PB_VM_T::nblks"

.PP
Definition at line 453 of file pblas\&.h\&.
.SS "int PB_VM_T::npcol"

.PP
Definition at line 457 of file pblas\&.h\&.
.SS "int PB_VM_T::nprow"

.PP
Definition at line 446 of file pblas\&.h\&.
.SS "int PB_VM_T::nq"

.PP
Definition at line 448 of file pblas\&.h\&.
.SS "int PB_VM_T::offd"

.PP
Definition at line 434 of file pblas\&.h\&.
.SS "int PB_VM_T::pcol"

.PP
Definition at line 456 of file pblas\&.h\&.
.SS "int PB_VM_T::prow"

.PP
Definition at line 445 of file pblas\&.h\&.
.SS "int PB_VM_T::upp"

.PP
Definition at line 444 of file pblas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
