.TH "SRC/pbchkvect.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pbchkvect.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tools\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDESCMULT\fP   100"
.br
.ti -1c
.RI "#define \fBBIGNUM\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpbchkvect\fP (int n, int npos0, int ix, int jx, desc_X, int incx, int dpos0, int *iix, int *jjx, int *ixrow, int *ixcol, int nprow, int npcol, int myrow, int mycol, int *info)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIGNUM   10000"

.SS "#define DESCMULT   100"

.SH "Function Documentation"
.PP 
.SS "void pbchkvect (int n, int npos0, int ix, int jx, desc_X, int incx, int dpos0, int * iix, int * jjx, int * ixrow, int * ixcol, int nprow, int npcol, int myrow, int mycol, int * info)"

.PP
Definition at line 15 of file pbchkvect\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
