.TH "PBLAS/SRC/PBBLAS/pbctrget.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PBBLAS/pbctrget.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpbctrget\fP (ICONTXT, ADIST, M, N, MNB, A, LDA, MCROW, MCCOL, IGD, MYROW, MYCOL, NPROW, NPCOL)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pbctrget (integer ICONTXT, character*1 ADIST, integer M, integer N, integer MNB, \fBcomplex\fP, dimension( lda, * ) A, integer LDA, integer MCROW, integer MCCOL, integer IGD, integer MYROW, integer MYCOL, integer NPROW, integer NPCOL)"

.PP
Definition at line 3 of file pbctrget\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
