.TH "SRC/pblas.h" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pblas.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcomplex\fP"
.br
.ti -1c
.RI "struct \fBcomplex16\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_HAL_\fP   0"
.br
.ti -1c
.RI "#define \fB_T3D_\fP   1"
.br
.ti -1c
.RI "#define \fB_MACH_\fP   \fB_HAL_\fP"
.br
.ti -1c
.RI "#define \fB_F2C_ADD_\fP   0"
.br
.ti -1c
.RI "#define \fB_F2C_NOCHANGE\fP   1"
.br
.ti -1c
.RI "#define \fB_F2C_UPCASE\fP   2"
.br
.ti -1c
.RI "#define \fB_F2C_F77ISF2C\fP   3"
.br
.ti -1c
.RI "#define \fB_F2C_CALL_\fP   \fB_F2C_ADD_\fP"
.br
.ti -1c
.RI "#define \fBF2C_CHAR\fP(a)   (a)"
.br
.ti -1c
.RI "#define \fBC2F_CHAR\fP(a)   (a)"
.br
.ti -1c
.RI "#define \fBF_VOID_FCT\fP   void                             /* Subroutine */"
.br
.ti -1c
.RI "#define \fBF_INTG_FCT\fP   int                        /* \fBINTEGER\fP function */"
.br
.ti -1c
.RI "#define \fBF_DBLE_FCT\fP   double            /* \fBDOUBLE\fP PRECISION function */"
.br
.ti -1c
.RI "#define \fBDLEN_\fP   9                     /* Length of a descriptor */"
.br
.ti -1c
.RI "#define \fBDT_\fP   0                     /* Descriptor Type        */"
.br
.ti -1c
.RI "#define \fBCTXT_\fP   1                              /* BLACS context */"
.br
.ti -1c
.RI "#define \fBM_\fP   2                      /* Global Number of Rows */"
.br
.ti -1c
.RI "#define \fBN_\fP   3                   /* Global Number of Columns */"
.br
.ti -1c
.RI "#define \fBMB_\fP   4                          /* Row Blocking Size */"
.br
.ti -1c
.RI "#define \fBNB_\fP   5                       /* Column Blocking Size */"
.br
.ti -1c
.RI "#define \fBRSRC_\fP   6                     /* Starting Processor Row */"
.br
.ti -1c
.RI "#define \fBCSRC_\fP   7                  /* Starting Processor Column */"
.br
.ti -1c
.RI "#define \fBLLD_\fP   8                    /* Local Leading Dimension */"
.br
.ti -1c
.RI "#define \fBBLOCK_CYCLIC_2D\fP   1"
.br
.ti -1c
.RI "#define \fBBLOCK_CYCLIC_INB_2D\fP   2"
.br
.ti -1c
.RI "#define \fBBROADCAST\fP   'B'              /* Blacs operation definitions */"
.br
.ti -1c
.RI "#define \fBCOMBINE\fP   'C'"
.br
.ti -1c
.RI "#define \fBALL\fP   'A'                        /* Scope definitions */"
.br
.ti -1c
.RI "#define \fBCOLUMN\fP   'C'"
.br
.ti -1c
.RI "#define \fBROW\fP   'R'"
.br
.ti -1c
.RI "#define \fBTOPDEF\fP   ' ' /* Default BLACS topology, PB\-BLAS routines */"
.br
.ti -1c
.RI "#define \fBCTOPDEF\fP   ' '"
.br
.ti -1c
.RI "#define \fBTOPGET\fP   '!'"
.br
.ti -1c
.RI "#define \fBYES\fP   'Y'"
.br
.ti -1c
.RI "#define \fBNO\fP   'N'"
.br
.ti -1c
.RI "#define \fBMULLENFAC\fP   2"
.br
.ti -1c
.RI "#define \fBONE\fP   1\&.0"
.br
.ti -1c
.RI "#define \fBZERO\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBABS\fP(a)   (((a) < 0) ? \-(a) : (a))"
.br
.ti -1c
.RI "#define \fBMIN\fP(a,  b)   (((a) < (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBMAX\fP(a,  b)   (((a) > (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBCEIL\fP(a,  b)   ( ((a)+(b)\-1) / (b) )"
.br
.ti -1c
.RI "#define \fBMlowcase\fP(C)   ( ((C) > 64 && (C) < 91) ? (C) | 32 : (C) )"
.br
.ti -1c
.RI "#define \fBMupcase\fP(C)   ( ((C) > 96 && (C) < 123) ? (C) & 0xDF : (C) )"
.br
.ti -1c
.RI "#define \fBINDXG2L\fP(iglob,  nb,  iproc,  isrcproc,  nprocs)"
.br
.ti -1c
.RI "#define \fBINDXL2G\fP(iloc,  nb,  iproc,  isrcproc,  nprocs)"
.br
.ti -1c
.RI "#define \fBINDXG2P\fP(iglob,  nb,  iproc,  isrcproc,  nprocs)   ( ( (isrcproc) + ( (iglob) \- 1 ) / (nb) ) % (nprocs) )"
.br
.ti -1c
.RI "#define \fBMYROC0\fP(nblocks,  n,  nb,  nprocs)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char * \fBF_CHAR\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _F2C_ADD_   0"

.PP
Definition at line 61 of file pblas\&.h\&.
.SS "#define _F2C_CALL_   \fB_F2C_ADD_\fP"

.PP
Definition at line 83 of file pblas\&.h\&.
.SS "#define _F2C_F77ISF2C   3"

.PP
Definition at line 64 of file pblas\&.h\&.
.SS "#define _F2C_NOCHANGE   1"

.PP
Definition at line 62 of file pblas\&.h\&.
.SS "#define _F2C_UPCASE   2"

.PP
Definition at line 63 of file pblas\&.h\&.
.SS "#define _HAL_   0"

.PP
Definition at line 22 of file pblas\&.h\&.
.SS "#define _MACH_   \fB_HAL_\fP"

.PP
Definition at line 30 of file pblas\&.h\&.
.SS "#define _T3D_   1"

.PP
Definition at line 23 of file pblas\&.h\&.
.SS "#define ABS(a)   (((a) < 0) ? \-(a) : (a))"

.PP
Definition at line 167 of file pblas\&.h\&.
.SS "#define ALL   'A'                        /* Scope definitions */"

.PP
Definition at line 145 of file pblas\&.h\&.
.SS "#define BLOCK_CYCLIC_2D   1"

.PP
Definition at line 139 of file pblas\&.h\&.
.SS "#define BLOCK_CYCLIC_INB_2D   2"

.PP
Definition at line 140 of file pblas\&.h\&.
.SS "#define BROADCAST   'B'              /* Blacs operation definitions */"

.PP
Definition at line 142 of file pblas\&.h\&.
.SS "#define C2F_CHAR(a)   (a)"

.PP
Definition at line 112 of file pblas\&.h\&.
.SS "#define CEIL(a, b)   ( ((a)+(b)\-1) / (b) )"

.PP
Definition at line 173 of file pblas\&.h\&.
.SS "#define COLUMN   'C'"

.PP
Definition at line 146 of file pblas\&.h\&.
.SS "#define COMBINE   'C'"

.PP
Definition at line 143 of file pblas\&.h\&.
.SS "#define CSRC_   7                  /* Starting Processor Column */"

.PP
Definition at line 133 of file pblas\&.h\&.
.SS "#define CTOPDEF   ' '"

.PP
Definition at line 150 of file pblas\&.h\&.
.SS "#define CTXT_   1                              /* BLACS context */"

.PP
Definition at line 127 of file pblas\&.h\&.
.SS "#define DLEN_   9                     /* Length of a descriptor */"

.PP
Definition at line 125 of file pblas\&.h\&.
.SS "#define DT_   0                     /* Descriptor Type        */"

.PP
Definition at line 126 of file pblas\&.h\&.
.SS "#define F2C_CHAR(a)   (a)"

.PP
Definition at line 111 of file pblas\&.h\&.
.SS "#define F_DBLE_FCT   double            /* \fBDOUBLE\fP PRECISION function */"

.PP
Definition at line 116 of file pblas\&.h\&.
.SS "#define F_INTG_FCT   int                        /* \fBINTEGER\fP function */"

.PP
Definition at line 115 of file pblas\&.h\&.
.SS "#define F_VOID_FCT   void                             /* Subroutine */"

.PP
Definition at line 114 of file pblas\&.h\&.
.SS "#define INDXG2L(iglob, nb, iproc, isrcproc, nprocs)"
\fBValue:\fP
.PP
.nf
( (nb) * ( ( (iglob)-1) / ( (nb) * (nprocs) ) ) +\
      ( ( (iglob) - 1 ) % (nb) ) + 1 )
.fi
.PP
Definition at line 179 of file pblas\&.h\&.
.SS "#define INDXG2P(iglob, nb, iproc, isrcproc, nprocs)   ( ( (isrcproc) + ( (iglob) \- 1 ) / (nb) ) % (nprocs) )"

.PP
Definition at line 188 of file pblas\&.h\&.
.SS "#define INDXL2G(iloc, nb, iproc, isrcproc, nprocs)"
\fBValue:\fP
.PP
.nf
( (nprocs) * (nb) * ( ( (iloc) - 1 ) / (nb) ) +\
      ( ( (iloc) - 1 ) % (nb) ) +\
      ( ( (nprocs) + (iproc) - (isrcproc) ) % (nprocs) ) * (nb) + 1 )
.fi
.PP
Definition at line 183 of file pblas\&.h\&.
.SS "#define LLD_   8                    /* Local Leading Dimension */"

.PP
Definition at line 134 of file pblas\&.h\&.
.SS "#define M_   2                      /* Global Number of Rows */"

.PP
Definition at line 128 of file pblas\&.h\&.
.SS "#define MAX(a, b)   (((a) > (b)) ? (a) : (b))"

.PP
Definition at line 171 of file pblas\&.h\&.
.SS "#define MB_   4                          /* Row Blocking Size */"

.PP
Definition at line 130 of file pblas\&.h\&.
.SS "#define MIN(a, b)   (((a) < (b)) ? (a) : (b))"

.PP
Definition at line 169 of file pblas\&.h\&.
.SS "#define Mlowcase(C)   ( ((C) > 64 && (C) < 91) ? (C) | 32 : (C) )"

.PP
Definition at line 175 of file pblas\&.h\&.
.SS "#define MULLENFAC   2"

.PP
Definition at line 156 of file pblas\&.h\&.
.SS "#define Mupcase(C)   ( ((C) > 96 && (C) < 123) ? (C) & 0xDF : (C) )"

.PP
Definition at line 177 of file pblas\&.h\&.
.SS "#define MYROC0(nblocks, n, nb, nprocs)"
\fBValue:\fP
.PP
.nf
( ( (nblocks) % (nprocs) ) ? ( ( (nblocks) / (nprocs) ) * (nb) + (nb) )\
                   : ( ( (nblocks) / (nprocs) )* (nb) + ( (n) % (nb) ) ) )
.fi
.PP
Definition at line 191 of file pblas\&.h\&.
.SS "#define N_   3                   /* Global Number of Columns */"

.PP
Definition at line 129 of file pblas\&.h\&.
.SS "#define NB_   5                       /* Column Blocking Size */"

.PP
Definition at line 131 of file pblas\&.h\&.
.SS "#define NO   'N'"

.PP
Definition at line 154 of file pblas\&.h\&.
.SS "#define ONE   1\&.0"

.PP
Definition at line 158 of file pblas\&.h\&.
.SS "#define ROW   'R'"

.PP
Definition at line 147 of file pblas\&.h\&.
.SS "#define RSRC_   6                     /* Starting Processor Row */"

.PP
Definition at line 132 of file pblas\&.h\&.
.SS "#define TOPDEF   ' ' /* Default BLACS topology, PB\-BLAS routines */"

.PP
Definition at line 149 of file pblas\&.h\&.
.SS "#define TOPGET   '!'"

.PP
Definition at line 151 of file pblas\&.h\&.
.SS "#define YES   'Y'"

.PP
Definition at line 153 of file pblas\&.h\&.
.SS "#define ZERO   0\&.0"

.PP
Definition at line 159 of file pblas\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef char* \fBF_CHAR\fP"

.PP
Definition at line 109 of file pblas\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
