.TH "PBLAS/SRC/PBBLAS/pbsvecadd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PBBLAS/pbsvecadd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpbsvecadd\fP (ICONTXT, MODE, N, ALPHA, X, INCX, BETA, Y, INCY)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pbsvecadd (integer ICONTXT, character*1 MODE, integer N, real ALPHA, real, dimension( * ) X, integer INCX, real BETA, real, dimension( * ) Y, integer INCY)"

.PP
Definition at line 3 of file pbsvecadd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
