.TH "PBTYP_T" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBTYP_T
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pblas\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "int \fBusiz\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "char * \fBzero\fP"
.br
.ti -1c
.RI "char * \fBone\fP"
.br
.ti -1c
.RI "char * \fBnegone\fP"
.br
.ti -1c
.RI "\fBGESD2D_T\fP \fBCgesd2d\fP"
.br
.ti -1c
.RI "\fBGERV2D_T\fP \fBCgerv2d\fP"
.br
.ti -1c
.RI "\fBGEBS2D_T\fP \fBCgebs2d\fP"
.br
.ti -1c
.RI "\fBGEBR2D_T\fP \fBCgebr2d\fP"
.br
.ti -1c
.RI "\fBGSUM2D_T\fP \fBCgsum2d\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmadd\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmcadd\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmtadd\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmtcadd\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmdda\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmddac\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmddat\fP"
.br
.ti -1c
.RI "\fBMMADD_T\fP \fBFmmddact\fP"
.br
.ti -1c
.RI "\fBMMSHFT_T\fP \fBFcshft\fP"
.br
.ti -1c
.RI "\fBMMSHFT_T\fP \fBFrshft\fP"
.br
.ti -1c
.RI "\fBVVDOT_T\fP \fBFvvdotu\fP"
.br
.ti -1c
.RI "\fBVVDOT_T\fP \fBFvvdotc\fP"
.br
.ti -1c
.RI "\fBTZPAD_T\fP \fBFtzpad\fP"
.br
.ti -1c
.RI "\fBTZPADCPY_T\fP \fBFtzpadcpy\fP"
.br
.ti -1c
.RI "\fBVVSET_T\fP \fBFset\fP"
.br
.ti -1c
.RI "\fBTZSCAL_T\fP \fBFtzscal\fP"
.br
.ti -1c
.RI "\fBTZSCAL_T\fP \fBFhescal\fP"
.br
.ti -1c
.RI "\fBTZSCAL_T\fP \fBFtzcnjg\fP"
.br
.ti -1c
.RI "\fBAXPY_T\fP \fBFaxpy\fP"
.br
.ti -1c
.RI "\fBCOPY_T\fP \fBFcopy\fP"
.br
.ti -1c
.RI "\fBSWAP_T\fP \fBFswap\fP"
.br
.ti -1c
.RI "\fBGEMV_T\fP \fBFgemv\fP"
.br
.ti -1c
.RI "\fBSYMV_T\fP \fBFsymv\fP"
.br
.ti -1c
.RI "\fBHEMV_T\fP \fBFhemv\fP"
.br
.ti -1c
.RI "\fBTRMV_T\fP \fBFtrmv\fP"
.br
.ti -1c
.RI "\fBTRSV_T\fP \fBFtrsv\fP"
.br
.ti -1c
.RI "\fBAGEMV_T\fP \fBFagemv\fP"
.br
.ti -1c
.RI "\fBASYMV_T\fP \fBFasymv\fP"
.br
.ti -1c
.RI "\fBAHEMV_T\fP \fBFahemv\fP"
.br
.ti -1c
.RI "\fBATRMV_T\fP \fBFatrmv\fP"
.br
.ti -1c
.RI "\fBGERC_T\fP \fBFgerc\fP"
.br
.ti -1c
.RI "\fBGERU_T\fP \fBFgeru\fP"
.br
.ti -1c
.RI "\fBSYR_T\fP \fBFsyr\fP"
.br
.ti -1c
.RI "\fBHER_T\fP \fBFher\fP"
.br
.ti -1c
.RI "\fBSYR2_T\fP \fBFsyr2\fP"
.br
.ti -1c
.RI "\fBHER2_T\fP \fBFher2\fP"
.br
.ti -1c
.RI "\fBGEMM_T\fP \fBFgemm\fP"
.br
.ti -1c
.RI "\fBSYMM_T\fP \fBFsymm\fP"
.br
.ti -1c
.RI "\fBHEMM_T\fP \fBFhemm\fP"
.br
.ti -1c
.RI "\fBSYRK_T\fP \fBFsyrk\fP"
.br
.ti -1c
.RI "\fBHERK_T\fP \fBFherk\fP"
.br
.ti -1c
.RI "\fBSYR2K_T\fP \fBFsyr2k\fP"
.br
.ti -1c
.RI "\fBHER2K_T\fP \fBFher2k\fP"
.br
.ti -1c
.RI "\fBTRMM_T\fP \fBFtrmm\fP"
.br
.ti -1c
.RI "\fBTRSM_T\fP \fBFtrsm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 325 of file pblas\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBGEBR2D_T\fP PBTYP_T::Cgebr2d"

.PP
Definition at line 338 of file pblas\&.h\&.
.SS "\fBGEBS2D_T\fP PBTYP_T::Cgebs2d"

.PP
Definition at line 337 of file pblas\&.h\&.
.SS "\fBGERV2D_T\fP PBTYP_T::Cgerv2d"

.PP
Definition at line 336 of file pblas\&.h\&.
.SS "\fBGESD2D_T\fP PBTYP_T::Cgesd2d"

.PP
Definition at line 335 of file pblas\&.h\&.
.SS "\fBGSUM2D_T\fP PBTYP_T::Cgsum2d"

.PP
Definition at line 339 of file pblas\&.h\&.
.SS "\fBAGEMV_T\fP PBTYP_T::Fagemv"

.PP
Definition at line 374 of file pblas\&.h\&.
.SS "\fBAHEMV_T\fP PBTYP_T::Fahemv"

.PP
Definition at line 376 of file pblas\&.h\&.
.SS "\fBASYMV_T\fP PBTYP_T::Fasymv"

.PP
Definition at line 375 of file pblas\&.h\&.
.SS "\fBATRMV_T\fP PBTYP_T::Fatrmv"

.PP
Definition at line 377 of file pblas\&.h\&.
.SS "\fBAXPY_T\fP PBTYP_T::Faxpy"

.PP
Definition at line 364 of file pblas\&.h\&.
.SS "\fBCOPY_T\fP PBTYP_T::Fcopy"

.PP
Definition at line 365 of file pblas\&.h\&.
.SS "\fBMMSHFT_T\fP PBTYP_T::Fcshft"

.PP
Definition at line 350 of file pblas\&.h\&.
.SS "\fBGEMM_T\fP PBTYP_T::Fgemm"

.PP
Definition at line 386 of file pblas\&.h\&.
.SS "\fBGEMV_T\fP PBTYP_T::Fgemv"

.PP
Definition at line 368 of file pblas\&.h\&.
.SS "\fBGERC_T\fP PBTYP_T::Fgerc"

.PP
Definition at line 379 of file pblas\&.h\&.
.SS "\fBGERU_T\fP PBTYP_T::Fgeru"

.PP
Definition at line 380 of file pblas\&.h\&.
.SS "\fBHEMM_T\fP PBTYP_T::Fhemm"

.PP
Definition at line 388 of file pblas\&.h\&.
.SS "\fBHEMV_T\fP PBTYP_T::Fhemv"

.PP
Definition at line 370 of file pblas\&.h\&.
.SS "\fBHER_T\fP PBTYP_T::Fher"

.PP
Definition at line 382 of file pblas\&.h\&.
.SS "\fBHER2_T\fP PBTYP_T::Fher2"

.PP
Definition at line 384 of file pblas\&.h\&.
.SS "\fBHER2K_T\fP PBTYP_T::Fher2k"

.PP
Definition at line 392 of file pblas\&.h\&.
.SS "\fBHERK_T\fP PBTYP_T::Fherk"

.PP
Definition at line 390 of file pblas\&.h\&.
.SS "\fBTZSCAL_T\fP PBTYP_T::Fhescal"

.PP
Definition at line 361 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmadd"

.PP
Definition at line 341 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmcadd"

.PP
Definition at line 342 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmdda"

.PP
Definition at line 345 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmddac"

.PP
Definition at line 346 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmddact"

.PP
Definition at line 348 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmddat"

.PP
Definition at line 347 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmtadd"

.PP
Definition at line 343 of file pblas\&.h\&.
.SS "\fBMMADD_T\fP PBTYP_T::Fmmtcadd"

.PP
Definition at line 344 of file pblas\&.h\&.
.SS "\fBMMSHFT_T\fP PBTYP_T::Frshft"

.PP
Definition at line 351 of file pblas\&.h\&.
.SS "\fBVVSET_T\fP PBTYP_T::Fset"

.PP
Definition at line 358 of file pblas\&.h\&.
.SS "\fBSWAP_T\fP PBTYP_T::Fswap"

.PP
Definition at line 366 of file pblas\&.h\&.
.SS "\fBSYMM_T\fP PBTYP_T::Fsymm"

.PP
Definition at line 387 of file pblas\&.h\&.
.SS "\fBSYMV_T\fP PBTYP_T::Fsymv"

.PP
Definition at line 369 of file pblas\&.h\&.
.SS "\fBSYR_T\fP PBTYP_T::Fsyr"

.PP
Definition at line 381 of file pblas\&.h\&.
.SS "\fBSYR2_T\fP PBTYP_T::Fsyr2"

.PP
Definition at line 383 of file pblas\&.h\&.
.SS "\fBSYR2K_T\fP PBTYP_T::Fsyr2k"

.PP
Definition at line 391 of file pblas\&.h\&.
.SS "\fBSYRK_T\fP PBTYP_T::Fsyrk"

.PP
Definition at line 389 of file pblas\&.h\&.
.SS "\fBTRMM_T\fP PBTYP_T::Ftrmm"

.PP
Definition at line 393 of file pblas\&.h\&.
.SS "\fBTRMV_T\fP PBTYP_T::Ftrmv"

.PP
Definition at line 371 of file pblas\&.h\&.
.SS "\fBTRSM_T\fP PBTYP_T::Ftrsm"

.PP
Definition at line 394 of file pblas\&.h\&.
.SS "\fBTRSV_T\fP PBTYP_T::Ftrsv"

.PP
Definition at line 372 of file pblas\&.h\&.
.SS "\fBTZSCAL_T\fP PBTYP_T::Ftzcnjg"

.PP
Definition at line 362 of file pblas\&.h\&.
.SS "\fBTZPAD_T\fP PBTYP_T::Ftzpad"

.PP
Definition at line 356 of file pblas\&.h\&.
.SS "\fBTZPADCPY_T\fP PBTYP_T::Ftzpadcpy"

.PP
Definition at line 357 of file pblas\&.h\&.
.SS "\fBTZSCAL_T\fP PBTYP_T::Ftzscal"

.PP
Definition at line 360 of file pblas\&.h\&.
.SS "\fBVVDOT_T\fP PBTYP_T::Fvvdotc"

.PP
Definition at line 354 of file pblas\&.h\&.
.SS "\fBVVDOT_T\fP PBTYP_T::Fvvdotu"

.PP
Definition at line 353 of file pblas\&.h\&.
.SS "char * PBTYP_T::negone"

.PP
Definition at line 331 of file pblas\&.h\&.
.SS "char * PBTYP_T::one"

.PP
Definition at line 331 of file pblas\&.h\&.
.SS "int PBTYP_T::size"

.PP
Definition at line 329 of file pblas\&.h\&.
.SS "char PBTYP_T::type"

.PP
Definition at line 327 of file pblas\&.h\&.
.SS "int PBTYP_T::usiz"

.PP
Definition at line 328 of file pblas\&.h\&.
.SS "char* PBTYP_T::zero"

.PP
Definition at line 331 of file pblas\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
