.TH "PBLAS/SRC/PBBLAS/pbztran.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PBBLAS/pbztran.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpbztran\fP (ICONTXT, ADIST, TRANS, M, N, NB, A, LDA, BETA, C, LDC, IAROW, IACOL, ICROW, ICCOL, WORK)"
.br
.ti -1c
.RI "subroutine \fBpbztr2at\fP (ICONTXT, ADIST, TRANS, M, N, NB, A, LDA, BETA, B, LDB, LCMP, LCMQ)"
.br
.ti -1c
.RI "subroutine \fBpbztr2bt\fP (ICONTXT, ADIST, TRANS, M, N, NB, A, LDA, BETA, B, LDB, INTV)"
.br
.ti -1c
.RI "subroutine \fBpbztr2af\fP (ICONTXT, ADIST, M, N, NB, A, LDA, BETA, B, LDB, LCMP, LCMQ, NINT)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pbztr2af (integer ICONTXT, character*1 ADIST, integer M, integer N, integer NB, \fBcomplex\fP*16, dimension( lda, * ) A, integer LDA, \fBcomplex\fP*16 BETA, \fBcomplex\fP*16, dimension( ldb, * ) B, integer LDB, integer LCMP, integer LCMQ, integer NINT)"

.PP
Definition at line 793 of file pbztran\&.f\&.
.SS "subroutine pbztr2at (integer ICONTXT, character*1 ADIST, character*1 TRANS, integer M, integer N, integer NB, \fBcomplex\fP*16, dimension( lda, * ) A, integer LDA, \fBcomplex\fP*16 BETA, \fBcomplex\fP*16, dimension( ldb, * ) B, integer LDB, integer LCMP, integer LCMQ)"

.PP
Definition at line 615 of file pbztran\&.f\&.
.SS "subroutine pbztr2bt (integer ICONTXT, character*1 ADIST, character*1 TRANS, integer M, integer N, integer NB, \fBcomplex\fP*16, dimension( lda, * ) A, integer LDA, \fBcomplex\fP*16 BETA, \fBcomplex\fP*16, dimension( ldb, * ) B, integer LDB, integer INTV)"

.PP
Definition at line 706 of file pbztran\&.f\&.
.SS "subroutine pbztran (integer ICONTXT, character*1 ADIST, character*1 TRANS, integer M, integer N, integer NB, \fBcomplex\fP*16, dimension( lda, * ) A, integer LDA, \fBcomplex\fP*16 BETA, \fBcomplex\fP*16, dimension( ldc, * ) C, integer LDC, integer IAROW, integer IACOL, integer ICROW, integer ICCOL, \fBcomplex\fP*16, dimension( * ) WORK)"

.PP
Definition at line 3 of file pbztran\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
