.TH "TOOLS/pccol2row.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pccol2row.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpccol2row\fP (ICTXT, M, N, NB, VS, LDVS, VD, LDVD, RSRC, CSRC, RDEST, CDEST, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pccol2row (integer ICTXT, integer M, integer N, integer NB, \fBcomplex\fP, dimension( ldvs, * ) VS, integer LDVS, \fBcomplex\fP, dimension( ldvd, * ) VD, integer LDVD, integer RSRC, integer CSRC, integer RDEST, integer CDEST, \fBcomplex\fP, dimension( * ) WORK)"

.PP
Definition at line 3 of file pccol2row\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
