.TH "TESTING/LIN/pcdbmv1.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pcdbmv1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcgbdcmv\fP (LDBW, BWL, BWU, TRANS, N, A, JA, DESCA, NRHS, B, IB, DESCB, X, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcgbdcmv (integer LDBW, integer BWL, integer BWU, character TRANS, integer N, \fBcomplex\fP, dimension( * ) A, integer JA, integer, dimension( * ) DESCA, integer NRHS, \fBcomplex\fP, dimension( * ) B, integer IB, integer, dimension( * ) DESCB, \fBcomplex\fP, dimension( * ) X, \fBcomplex\fP, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pcdbmv1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
