.TH "TESTING/LIN/pcdtinfo.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pcdtinfo.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcdtinfo\fP (SUMMRY, NOUT, TRANS, NMAT, NVAL, LDNVAL, NBW, BWLVAL, BWUVAL, LDBWVAL, NNB, NBVAL, LDNBVAL, NNR, NRVAL, LDNRVAL, NNBR, NBRVAL, LDNBRVAL, NGRIDS, PVAL, LDPVAL, QVAL, LDQVAL, THRESH, WORK, IAM, NPROCS)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcdtinfo (character*(*) SUMMRY, integer NOUT, character TRANS, integer NMAT, integer, dimension( ldnval ) NVAL, integer LDNVAL, integer NBW, integer, dimension( ldbwval) BWLVAL, integer, dimension( ldbwval) BWUVAL, integer LDBWVAL, integer NNB, integer, dimension( ldnbval ) NBVAL, integer LDNBVAL, integer NNR, integer, dimension( ldnrval ) NRVAL, integer LDNRVAL, integer NNBR, integer, dimension( ldnbrval ) NBRVAL, integer LDNBRVAL, integer NGRIDS, integer, dimension( ldpval ) PVAL, integer LDPVAL, integer, dimension(ldqval) QVAL, integer LDQVAL, real THRESH, integer, dimension( * ) WORK, integer IAM, integer NPROCS)"

.PP
Definition at line 6 of file pcdtinfo\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
