.TH "SRC/pcgesv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pcgesv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcgesv\fP (N, NRHS, A, IA, JA, DESCA, IPIV, B, IB, JB, DESCB, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcgesv (integer N, integer NRHS, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( * ) IPIV, \fBcomplex\fP, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, integer INFO)"

.PP
Definition at line 3 of file pcgesv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
