.TH "SRC/pcgesvd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pcgesvd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcgesvd\fP (JOBU, JOBVT, M, N, A, IA, JA, DESCA, S, U, IU, JU, DESCU, VT, IVT, JVT, DESCVT, WORK, LWORK, RWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcgesvd (character JOBU, character JOBVT, integer M, integer N, \fBcomplex\fP, dimension(*) A, integer IA, integer JA, integer, dimension(*) DESCA, real, dimension(*) S, \fBcomplex\fP, dimension(*) U, integer IU, integer JU, integer, dimension(*) DESCU, \fBcomplex\fP, dimension(*) VT, integer IVT, integer JVT, integer, dimension(*) DESCVT, \fBcomplex\fP, dimension(*) WORK, integer LWORK, real, dimension(*) RWORK, integer INFO)"

.PP
Definition at line 4 of file pcgesvd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
