.TH "TESTING/EIG/pcgsepsubtst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pcgsepsubtst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcgsepsubtst\fP (WKNOWN, IBTYPE, JOBZ, RANGE, UPLO, N, VL, VU, IL, IU, THRESH, ABSTOL, A, COPYA, B, COPYB, Z, IA, JA, DESCA, WIN, WNEW, IFAIL, ICLUSTR, GAP, IPREPAD, IPOSTPAD, WORK, LWORK, RWORK, LRWORK, LWORK1, IWORK, LIWORK, RESULT, TSTNRM, QTQNRM, NOUT)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcgsepsubtst (logical WKNOWN, integer IBTYPE, character JOBZ, character RANGE, character UPLO, integer N, real VL, real VU, integer IL, integer IU, real THRESH, real ABSTOL, \fBcomplex\fP, dimension( * ) A, \fBcomplex\fP, dimension( * ) COPYA, \fBcomplex\fP, dimension( * ) B, \fBcomplex\fP, dimension( * ) COPYB, \fBcomplex\fP, dimension( * ) Z, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) WIN, real, dimension( * ) WNEW, integer, dimension( * ) IFAIL, integer, dimension( * ) ICLUSTR, real, dimension( * ) GAP, integer IPREPAD, integer IPOSTPAD, \fBcomplex\fP, dimension( * ) WORK, integer LWORK, real, dimension( * ) RWORK, integer LRWORK, integer LWORK1, integer, dimension( * ) IWORK, integer LIWORK, integer RESULT, real TSTNRM, real QTQNRM, integer NOUT)"

.PP
Definition at line 10 of file pcgsepsubtst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
