.TH "TESTING/EIG/pcgseptst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pcgseptst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcgseptst\fP (DESCA, UPLO, N, MATTYPE, IBTYPE, SUBTESTS, THRESH, ORDER, ABSTOL, ISEED, A, COPYA, B, COPYB, Z, LDA, WIN, WNEW, IFAIL, ICLUSTR, GAP, IPREPAD, IPOSTPAD, WORK, LWORK, RWORK, LRWORK, IWORK, LIWORK, NOUT, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcgseptst (integer, dimension( * ) DESCA, character UPLO, integer N, integer MATTYPE, integer IBTYPE, character SUBTESTS, real THRESH, integer ORDER, real ABSTOL, integer, dimension( 4 ) ISEED, \fBcomplex\fP, dimension( lda, * ) A, \fBcomplex\fP, dimension( lda, * ) COPYA, \fBcomplex\fP, dimension( lda, * ) B, \fBcomplex\fP, dimension( lda, * ) COPYB, \fBcomplex\fP, dimension( lda, * ) Z, integer LDA, real, dimension( * ) WIN, real, dimension( * ) WNEW, integer, dimension( * ) IFAIL, integer, dimension( * ) ICLUSTR, real, dimension( * ) GAP, integer IPREPAD, integer IPOSTPAD, \fBcomplex\fP, dimension( * ) WORK, integer LWORK, real, dimension( * ) RWORK, integer LRWORK, integer, dimension( * ) IWORK, integer LIWORK, integer NOUT, integer INFO)"

.PP
Definition at line 8 of file pcgseptst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
