.TH "PBLAS/SRC/pcher2_.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/pcher2_.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pblas\&.h'\fP
.br
\fC#include 'PBpblas\&.h'\fP
.br
\fC#include 'PBtools\&.h'\fP
.br
\fC#include 'PBblacs\&.h'\fP
.br
\fC#include 'PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpcher2_\fP (\fBF_CHAR_T\fP UPLO, int *N, float *ALPHA, float *X, int *IX, int *JX, int *DESCX, int *INCX, float *Y, int *IY, int *JY, int *DESCY, int *INCY, float *A, int *IA, int *JA, int *DESCA)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pcher2_ (\fBF_CHAR_T\fP UPLO, int                  * N, float          * ALPHA, float * X, int * IX, int * JX, int * DESCX, int * INCX, float * Y, int * IY, int * JY, int * DESCY, int * INCY, float          * A, int            * IA, int * JA, int            * DESCA)"

.PP
Definition at line 25 of file pcher2_\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
