.TH "SRC/pclapv2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pclapv2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpclapv2\fP (DIREC, ROWCOL, M, N, A, IA, JA, DESCA, IPIV, IP, JP, DESCIP)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pclapv2 (character DIREC, character ROWCOL, integer M, integer N, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( * ) IPIV, integer IP, integer JP, integer, dimension( * ) DESCIP)"

.PP
Definition at line 3 of file pclapv2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
