.TH "SRC/pclarzc.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pclarzc.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpclarzc\fP (SIDE, M, N, L, V, IV, JV, DESCV, INCV, TAU, C, IC, JC, DESCC, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pclarzc (character SIDE, integer M, integer N, integer L, \fBcomplex\fP, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, integer INCV, \fBcomplex\fP, dimension( * ) TAU, \fBcomplex\fP, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, \fBcomplex\fP, dimension( * ) WORK)"

.PP
Definition at line 3 of file pclarzc\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
