.TH "SRC/pclaset.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pclaset.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpclaset\fP (UPLO, M, N, ALPHA, BETA, A, IA, JA, DESCA)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pclaset (character UPLO, integer M, integer N, \fBcomplex\fP ALPHA, \fBcomplex\fP BETA, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA)"

.PP
Definition at line 2 of file pclaset\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
