.TH "TESTING/EIG/pclasizesepr.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pclasizesepr.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpclasizesepr\fP (DESCA, IPREPAD, IPOSTPAD, SIZEMQRLEFT, SIZEMQRRIGHT, SIZEQRF, SIZETMS, SIZEQTQ, SIZECHK, SIZEHEEVR, RSIZEHEEVR, ISIZEHEEVR, SIZESUBTST, RSIZESUBTST, ISIZESUBTST, SIZETST, RSIZETST, ISIZETST)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pclasizesepr (integer, dimension( * ) DESCA, integer IPREPAD, integer IPOSTPAD, integer SIZEMQRLEFT, integer SIZEMQRRIGHT, integer SIZEQRF, integer SIZETMS, integer SIZEQTQ, integer SIZECHK, integer SIZEHEEVR, integer RSIZEHEEVR, integer ISIZEHEEVR, integer SIZESUBTST, integer RSIZESUBTST, integer ISIZESUBTST, integer SIZETST, integer RSIZETST, integer ISIZETST)"

.PP
Definition at line 7 of file pclasizesepr\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
