.TH "SRC/pclanhs.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pclanhs.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real function \fBpclanhs\fP (NORM, N, A, IA, JA, DESCA, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "real function pclanhs (character NORM, integer N, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) WORK)"

.PP
Definition at line 3 of file pclanhs\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
