.TH "SRC/pclatrd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pclatrd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpclatrd\fP (UPLO, N, NB, A, IA, JA, DESCA, D, E, TAU, W, IW, JW, DESCW, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pclatrd (character UPLO, integer N, integer NB, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) D, real, dimension( * ) E, \fBcomplex\fP, dimension( * ) TAU, \fBcomplex\fP, dimension( * ) W, integer IW, integer JW, integer, dimension( * ) DESCW, \fBcomplex\fP, dimension( * ) WORK)"

.PP
Definition at line 3 of file pclatrd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
