.TH "TOOLS/pcmatadd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pcmatadd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcmatadd\fP (M, N, ALPHA, A, IA, JA, DESCA, BETA, C, IC, JC, DESCC)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcmatadd (integer M, integer N, \fBcomplex\fP ALPHA, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP BETA, \fBcomplex\fP, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC)"

.PP
Definition at line 3 of file pcmatadd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
