.TH "SRC/pcmax1.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pcmax1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcmax1\fP (N, AMAX, INDX, X, IX, JX, DESCX, INCX)"
.br
.ti -1c
.RI "subroutine \fBccombamax1\fP (V1, V2)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ccombamax1 (\fBcomplex\fP, dimension( 2 ) V1, \fBcomplex\fP, dimension( 2 ) V2)"

.PP
Definition at line 361 of file pcmax1\&.f\&.
.SS "subroutine pcmax1 (integer N, \fBcomplex\fP AMAX, integer INDX, \fBcomplex\fP, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX)"

.PP
Definition at line 2 of file pcmax1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
