.TH "TESTING/EIG/pcnepfchk.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pcnepfchk.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcnepfchk\fP (N, A, IA, JA, DESCA, IASEED, Z, IZ, JZ, DESCZ, ANORM, FRESID, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcnepfchk (integer N, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer IASEED, \fBcomplex\fP, dimension( * ) Z, integer IZ, integer JZ, integer, dimension( * ) DESCZ, real ANORM, real FRESID, \fBcomplex\fP, dimension( * ) WORK)"

.PP
Definition at line 3 of file pcnepfchk\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
