.TH "TESTING/LIN/pcqrt14.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pcqrt14.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real function \fBpcqrt14\fP (TRANS, M, N, NRHS, A, IA, JA, DESCA, X, IX, JX, DESCX, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "real function pcqrt14 (character TRANS, integer M, integer N, integer NRHS, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, \fBcomplex\fP, dimension( * ) WORK)"

.PP
Definition at line 3 of file pcqrt14\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
