.TH "TESTING/LIN/pcqrt16.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pcqrt16.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcqrt16\fP (TRANS, M, N, NRHS, A, IA, JA, DESCA, X, IX, JX, DESCX, B, IB, JB, DESCB, RWORK, RESID)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcqrt16 (character TRANS, integer M, integer N, integer NRHS, \fBcomplex\fP, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, \fBcomplex\fP, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, real, dimension( * ) RWORK, real RESID)"

.PP
Definition at line 3 of file pcqrt16\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
