.TH "TESTING/LIN/pcqrinfo.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pcqrinfo.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpcqrinfo\fP (SUMMRY, NOUT, NFACT, FACTOR, LDFACT, NMAT, MVAL, LDMVAL, NVAL, LDNVAL, NNB, MBVAL, LDMBVAL, NBVAL, LDNBVAL, NGRIDS, PVAL, LDPVAL, QVAL, LDQVAL, THRESH, WORK, IAM, NPROCS)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pcqrinfo (character*(*) SUMMRY, integer NOUT, integer NFACT, character*2, dimension( ldfact ) FACTOR, integer LDFACT, integer NMAT, integer, dimension( ldmval ) MVAL, integer LDMVAL, integer, dimension( ldnval ) NVAL, integer LDNVAL, integer NNB, integer, dimension( ldmbval ) MBVAL, integer LDMBVAL, integer, dimension( ldnbval ) NBVAL, integer LDNBVAL, integer NGRIDS, integer, dimension( ldpval ) PVAL, integer LDPVAL, integer, dimension( ldqval ) QVAL, integer LDQVAL, real THRESH, integer, dimension( * ) WORK, integer IAM, integer NPROCS)"

.PP
Definition at line 6 of file pcqrinfo\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
