.TH "PBLAS/TESTING/pdblastst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/TESTING/pdblastst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdoptee\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME)"
.br
.ti -1c
.RI "subroutine \fBpdchkopt\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME, ARGNAM, ARGPOS)"
.br
.ti -1c
.RI "subroutine \fBpddimee\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME)"
.br
.ti -1c
.RI "subroutine \fBpdchkdim\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME, ARGNAM, ARGPOS)"
.br
.ti -1c
.RI "subroutine \fBpdvecee\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME)"
.br
.ti -1c
.RI "subroutine \fBpdmatee\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME)"
.br
.ti -1c
.RI "subroutine \fBpdsetpblas\fP (ICTXT)"
.br
.ti -1c
.RI "subroutine \fBpdchkmat\fP (ICTXT, NOUT, SUBPTR, SCODE, SNAME, ARGNAM, ARGPOS)"
.br
.ti -1c
.RI "subroutine \fBpdcallsub\fP (SUBPTR, SCODE)"
.br
.ti -1c
.RI "subroutine \fBpderrset\fP (ERR, ERRMAX, XTRUE, X)"
.br
.ti -1c
.RI "subroutine \fBpdchkvin\fP (ERRMAX, N, X, PX, IX, JX, DESCX, INCX, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdchkvout\fP (N, X, PX, IX, JX, DESCX, INCX, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdchkmin\fP (ERRMAX, M, N, A, PA, IA, JA, DESCA, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdchkmout\fP (M, N, A, PA, IA, JA, DESCA, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdmprnt\fP (ICTXT, NOUT, M, N, A, LDA, IRPRNT, ICPRNT, CMATNM)"
.br
.ti -1c
.RI "subroutine \fBpdvprnt\fP (ICTXT, NOUT, N, X, INCX, IRPRNT, ICPRNT, CVECNM)"
.br
.ti -1c
.RI "subroutine \fBpdmvch\fP (ICTXT, TRANS, M, N, ALPHA, A, IA, JA, DESCA, X, IX, JX, DESCX, INCX, BETA, Y, PY, IY, JY, DESCY, INCY, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdvmch\fP (ICTXT, UPLO, M, N, ALPHA, X, IX, JX, DESCX, INCX, Y, IY, JY, DESCY, INCY, A, PA, IA, JA, DESCA, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdvmch2\fP (ICTXT, UPLO, M, N, ALPHA, X, IX, JX, DESCX, INCX, Y, IY, JY, DESCY, INCY, A, PA, IA, JA, DESCA, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdmmch\fP (ICTXT, TRANSA, TRANSB, M, N, K, ALPHA, A, IA, JA, DESCA, B, IB, JB, DESCB, BETA, C, PC, IC, JC, DESCC, CT, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdmmch1\fP (ICTXT, UPLO, TRANS, N, K, ALPHA, A, IA, JA, DESCA, BETA, C, PC, IC, JC, DESCC, CT, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdmmch2\fP (ICTXT, UPLO, TRANS, N, K, ALPHA, A, IA, JA, DESCA, B, IB, JB, DESCB, BETA, C, PC, IC, JC, DESCC, CT, G, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpdmmch3\fP (UPLO, TRANS, M, N, ALPHA, A, IA, JA, DESCA, BETA, C, PC, IC, JC, DESCC, ERR, INFO)"
.br
.ti -1c
.RI "subroutine \fBpderraxpby\fP (ERRBND, ALPHA, X, BETA, Y, PREC)"
.br
.ti -1c
.RI "double precision function \fBpdlamch\fP (ICTXT, CMACH)"
.br
.ti -1c
.RI "subroutine \fBpdlaset\fP (UPLO, M, N, ALPHA, BETA, A, IA, JA, DESCA)"
.br
.ti -1c
.RI "subroutine \fBpdlascal\fP (\fBTYPE\fP, M, N, ALPHA, A, IA, JA, DESCA)"
.br
.ti -1c
.RI "subroutine \fBpdlagen\fP (INPLACE, AFORM, DIAG, OFFA, M, N, IA, JA, DESCA, IASEED, A, LDA)"
.br
.ti -1c
.RI "subroutine \fBpdladom\fP (INPLACE, N, ALPHA, A, IA, JA, DESCA)"
.br
.ti -1c
.RI "subroutine \fBpb_pdlaprnt\fP (M, N, A, IA, JA, DESCA, IRPRNT, ICPRNT, CMATNM, NOUT, WORK)"
.br
.ti -1c
.RI "subroutine \fBpb_pdlaprn2\fP (M, N, A, IA, JA, DESCA, IRPRNT, ICPRNT, CMATNM, NOUT, PROW, PCOL, WORK)"
.br
.ti -1c
.RI "subroutine \fBpb_dfillpad\fP (ICTXT, M, N, A, LDA, IPRE, IPOST, CHKVAL)"
.br
.ti -1c
.RI "subroutine \fBpb_dchekpad\fP (ICTXT, MESS, M, N, A, LDA, IPRE, IPOST, CHKVAL)"
.br
.ti -1c
.RI "subroutine \fBpb_dlaset\fP (UPLO, M, N, IOFFD, ALPHA, BETA, A, LDA)"
.br
.ti -1c
.RI "subroutine \fBpb_dlascal\fP (UPLO, M, N, IOFFD, ALPHA, A, LDA)"
.br
.ti -1c
.RI "subroutine \fBpb_dlagen\fP (UPLO, AFORM, A, LDA, LCMT00, IRAN, MBLKS, IMBLOC, MB, LMBLOC, NBLKS, INBLOC, NB, LNBLOC, JMP, IMULADD)"
.br
.ti -1c
.RI "double precision function \fBpb_drand\fP (IDUMM)"
.br
.ti -1c
.RI "double precision function \fBpb_dran\fP (IDUMM)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pb_dchekpad (integer ICTXT, character*(*) MESS, integer M, integer N, double precision, dimension( * ) A, integer LDA, integer IPRE, integer IPOST, double precision CHKVAL)"

.PP
Definition at line 9192 of file pdblastst\&.f\&.
.SS "subroutine pb_dfillpad (integer ICTXT, integer M, integer N, double precision, dimension( * ) A, integer LDA, integer IPRE, integer IPOST, double precision CHKVAL)"

.PP
Definition at line 9079 of file pdblastst\&.f\&.
.SS "subroutine pb_dlagen (character*1 UPLO, character*1 AFORM, double precision, dimension( lda, * ) A, integer LDA, integer LCMT00, integer, dimension( * ) IRAN, integer MBLKS, integer IMBLOC, integer MB, integer LMBLOC, integer NBLKS, integer INBLOC, integer NB, integer LNBLOC, integer, dimension( * ) JMP, integer, dimension( 4, * ) IMULADD)"

.PP
Definition at line 9737 of file pdblastst\&.f\&.
.SS "subroutine pb_dlascal (character*1 UPLO, integer M, integer N, integer IOFFD, double precision ALPHA, double precision, dimension( lda, * ) A, integer LDA)"

.PP
Definition at line 9556 of file pdblastst\&.f\&.
.SS "subroutine pb_dlaset (character*1 UPLO, integer M, integer N, integer IOFFD, double precision ALPHA, double precision BETA, double precision, dimension( lda, * ) A, integer LDA)"

.PP
Definition at line 9359 of file pdblastst\&.f\&.
.SS "double precision function pb_dran (integer IDUMM)"

.PP
Definition at line 10440 of file pdblastst\&.f\&.
.SS "double precision function pb_drand (integer IDUMM)"

.PP
Definition at line 10378 of file pdblastst\&.f\&.
.SS "subroutine pb_pdlaprn2 (integer M, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer IRPRNT, integer ICPRNT, character*(*) CMATNM, integer NOUT, integer PROW, integer PCOL, double precision, dimension( * ) WORK)"

.PP
Definition at line 8848 of file pdblastst\&.f\&.
.SS "subroutine pb_pdlaprnt (integer M, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer IRPRNT, integer ICPRNT, character*(*) CMATNM, integer NOUT, double precision, dimension( * ) WORK)"

.PP
Definition at line 8634 of file pdblastst\&.f\&.
.SS "subroutine pdcallsub (external SUBPTR, integer SCODE)"

.PP
Definition at line 2180 of file pdblastst\&.f\&.
.SS "subroutine pdchkdim (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*(*) SNAME, character*1 ARGNAM, integer ARGPOS)"

.PP
Definition at line 759 of file pdblastst\&.f\&.
.SS "subroutine pdchkmat (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*(*) SNAME, character*1 ARGNAM, integer ARGPOS)"

.PP
Definition at line 1674 of file pdblastst\&.f\&.
.SS "subroutine pdchkmin (double precision ERRMAX, integer M, integer N, double precision, dimension( * ) A, double precision, dimension( * ) PA, integer IA, integer JA, integer, dimension( * ) DESCA, integer INFO)"

.PP
Definition at line 3326 of file pdblastst\&.f\&.
.SS "subroutine pdchkmout (integer M, integer N, double precision, dimension( * ) A, double precision, dimension( * ) PA, integer IA, integer JA, integer, dimension( * ) DESCA, integer INFO)"

.PP
Definition at line 3627 of file pdblastst\&.f\&.
.SS "subroutine pdchkopt (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*(*) SNAME, character*1 ARGNAM, integer ARGPOS)"

.PP
Definition at line 266 of file pdblastst\&.f\&.
.SS "subroutine pdchkvin (double precision ERRMAX, integer N, double precision, dimension( * ) X, double precision, dimension( * ) PX, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, integer INFO)"

.PP
Definition at line 2576 of file pdblastst\&.f\&.
.SS "subroutine pdchkvout (integer N, double precision, dimension( * ) X, double precision, dimension( * ) PX, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, integer INFO)"

.PP
Definition at line 2870 of file pdblastst\&.f\&.
.SS "subroutine pddimee (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*(*) SNAME)"

.PP
Definition at line 455 of file pdblastst\&.f\&.
.SS "subroutine pderraxpby (double precision ERRBND, double precision ALPHA, double precision X, double precision BETA, double precision Y, double precision PREC)"

.PP
Definition at line 6684 of file pdblastst\&.f\&.
.SS "subroutine pderrset (double precision ERR, double precision ERRMAX, double precision XTRUE, double precision X)"

.PP
Definition at line 2456 of file pdblastst\&.f\&.
.SS "subroutine pdladom (logical INPLACE, integer N, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA)"

.PP
Definition at line 8242 of file pdblastst\&.f\&.
.SS "subroutine pdlagen (logical INPLACE, character*1 AFORM, character*1 DIAG, integer OFFA, integer M, integer N, integer IA, integer JA, integer, dimension( * ) DESCA, integer IASEED, double precision, dimension( lda, * ) A, integer LDA)"

.PP
Definition at line 7845 of file pdblastst\&.f\&.
.SS "double precision function pdlamch (integer ICTXT, character*1 CMACH)"

.PP
Definition at line 6769 of file pdblastst\&.f\&.
.SS "subroutine pdlascal (character*1 TYPE, integer M, integer N, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA)"

.PP
Definition at line 7337 of file pdblastst\&.f\&.
.SS "subroutine pdlaset (character*1 UPLO, integer M, integer N, double precision ALPHA, double precision BETA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA)"

.PP
Definition at line 6862 of file pdblastst\&.f\&.
.SS "subroutine pdmatee (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*7 SNAME)"

.PP
Definition at line 1190 of file pdblastst\&.f\&.
.SS "subroutine pdmmch (integer ICTXT, character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, double precision BETA, double precision, dimension( * ) C, double precision, dimension( * ) PC, integer IC, integer JC, integer, dimension( * ) DESCC, double precision, dimension( * ) CT, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 5272 of file pdblastst\&.f\&.
.SS "subroutine pdmmch1 (integer ICTXT, character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision BETA, double precision, dimension( * ) C, double precision, dimension( * ) PC, integer IC, integer JC, integer, dimension( * ) DESCC, double precision, dimension( * ) CT, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 5649 of file pdblastst\&.f\&.
.SS "subroutine pdmmch2 (integer ICTXT, character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, double precision BETA, double precision, dimension( * ) C, double precision, dimension( * ) PC, integer IC, integer JC, integer, dimension( * ) DESCC, double precision, dimension( * ) CT, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 5996 of file pdblastst\&.f\&.
.SS "subroutine pdmmch3 (character*1 UPLO, character*1 TRANS, integer M, integer N, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision BETA, double precision, dimension( * ) C, double precision, dimension( * ) PC, integer IC, integer JC, integer, dimension( * ) DESCC, double precision ERR, integer INFO)"

.PP
Definition at line 6372 of file pdblastst\&.f\&.
.SS "subroutine pdmprnt (integer ICTXT, integer NOUT, integer M, integer N, double precision, dimension( lda, * ) A, integer LDA, integer IRPRNT, integer ICPRNT, character*(*) CMATNM)"

.PP
Definition at line 3949 of file pdblastst\&.f\&.
.SS "subroutine pdmvch (integer ICTXT, character*1 TRANS, integer M, integer N, double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, double precision BETA, double precision, dimension( * ) Y, double precision, dimension( * ) PY, integer IY, integer JY, integer, dimension( * ) DESCY, integer INCY, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 4157 of file pdblastst\&.f\&.
.SS "subroutine pdoptee (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*(*) SNAME)"

.PP
Definition at line 2 of file pdblastst\&.f\&.
.SS "subroutine pdsetpblas (integer ICTXT)"

.PP
Definition at line 1478 of file pdblastst\&.f\&.
.SS "subroutine pdvecee (integer ICTXT, integer NOUT, external SUBPTR, integer SCODE, character*7 SNAME)"

.PP
Definition at line 936 of file pdblastst\&.f\&.
.SS "subroutine pdvmch (integer ICTXT, character*1 UPLO, integer M, integer N, double precision ALPHA, double precision, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, double precision, dimension( * ) Y, integer IY, integer JY, integer, dimension( * ) DESCY, integer INCY, double precision, dimension( * ) A, double precision, dimension( * ) PA, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 4570 of file pdblastst\&.f\&.
.SS "subroutine pdvmch2 (integer ICTXT, character*1 UPLO, integer M, integer N, double precision ALPHA, double precision, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, double precision, dimension( * ) Y, integer IY, integer JY, integer, dimension( * ) DESCY, integer INCY, double precision, dimension( * ) A, double precision, dimension( * ) PA, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) G, double precision ERR, integer INFO)"

.PP
Definition at line 4919 of file pdblastst\&.f\&.
.SS "subroutine pdvprnt (integer ICTXT, integer NOUT, integer N, double precision, dimension( * ) X, integer INCX, integer IRPRNT, integer ICPRNT, character*(*) CVECNM)"

.PP
Definition at line 4056 of file pdblastst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
