.TH "TOOLS/pdchekpad.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pdchekpad.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdchekpad\fP (ICTXT, MESS, M, N, A, LDA, IPRE, IPOST, CHKVAL)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdchekpad (integer ICTXT, character, dimension(*) MESS, integer M, integer N, double precision, dimension( * ) A, integer LDA, integer IPRE, integer IPOST, double precision CHKVAL)"

.PP
Definition at line 3 of file pdchekpad\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
