.TH "SRC/pddttrsv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pddttrsv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpddttrsv\fP (UPLO, TRANS, N, NRHS, DL, D, DU, JA, DESCA, B, IB, DESCB, AF, LAF, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pddttrsv (character UPLO, character TRANS, integer N, integer NRHS, double precision, dimension( * ) DL, double precision, dimension( * ) D, double precision, dimension( * ) DU, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) B, integer IB, integer, dimension( * ) DESCB, double precision, dimension( * ) AF, integer LAF, double precision, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pddttrsv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
