.TH "TOOLS/pdelset2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pdelset2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdelset2\fP (ALPHA, A, IA, JA, DESCA, BETA)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdelset2 (double precision ALPHA, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision BETA)"

.PP
Definition at line 2 of file pdelset2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
