.TH "SRC/pdgesv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdgesv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdgesv\fP (N, NRHS, A, IA, JA, DESCA, IPIV, B, IB, JB, DESCB, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdgesv (integer N, integer NRHS, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( * ) IPIV, double precision, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, integer INFO)"

.PP
Definition at line 3 of file pdgesv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
