.TH "TESTING/EIG/pdgseptst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pdgseptst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdgseptst\fP (DESCA, UPLO, N, MATTYPE, IBTYPE, SUBTESTS, THRESH, ORDER, ABSTOL, ISEED, A, COPYA, B, COPYB, Z, LDA, WIN, WNEW, IFAIL, ICLUSTR, GAP, IPREPAD, IPOSTPAD, WORK, LWORK, IWORK, LIWORK, NOUT, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdgseptst (integer, dimension( * ) DESCA, character UPLO, integer N, integer MATTYPE, integer IBTYPE, character SUBTESTS, double precision THRESH, integer ORDER, double precision ABSTOL, integer, dimension( 4 ) ISEED, double precision, dimension( lda, * ) A, double precision, dimension( lda, * ) COPYA, double precision, dimension( lda, * ) B, double precision, dimension( lda, * ) COPYB, double precision, dimension( lda, * ) Z, integer LDA, double precision, dimension( * ) WIN, double precision, dimension( * ) WNEW, integer, dimension( * ) IFAIL, integer, dimension( * ) ICLUSTR, double precision, dimension( * ) GAP, integer IPREPAD, integer IPOSTPAD, double precision, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer LIWORK, integer NOUT, integer INFO)"

.PP
Definition at line 8 of file pdgseptst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
