.TH "SRC/pdhseqr.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdhseqr.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdhseqr\fP (JOB, COMPZ, N, ILO, IHI, H, DESCH, WR, WI, Z, DESCZ, WORK, LWORK, IWORK, LIWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdhseqr (character JOB, character COMPZ, integer N, integer ILO, integer IHI, double precision, dimension( * ) H, integer, dimension( * ) DESCH, double precision, dimension( n ) WR, double precision, dimension( n ) WI, double precision, dimension( * ) Z, integer, dimension( * ) DESCZ, double precision, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer LIWORK, integer INFO)"

.PP
Definition at line 3 of file pdhseqr\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
