.TH "SRC/pdlacon.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdlacon.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlacon\fP (N, V, IV, JV, DESCV, X, IX, JX, DESCX, ISGN, EST, KASE)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlacon (integer N, double precision, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, double precision, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer, dimension( * ) ISGN, double precision EST, integer KASE)"

.PP
Definition at line 3 of file pdlacon\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
