.TH "SRC/pdlarfb.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdlarfb.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlarfb\fP (SIDE, TRANS, DIRECT, STOREV, M, N, K, V, IV, JV, DESCV, T, C, IC, JC, DESCC, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlarfb (character SIDE, character TRANS, character DIRECT, character STOREV, integer M, integer N, integer K, double precision, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, double precision, dimension( * ) T, double precision, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, double precision, dimension( * ) WORK)"

.PP
Definition at line 3 of file pdlarfb\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
