.TH "SRC/pdlaed1.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdlaed1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlaed1\fP (N, N1, D, ID, Q, IQ, JQ, DESCQ, RHO, WORK, IWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlaed1 (integer N, integer N1, double precision, dimension( * ) D, integer ID, double precision, dimension( * ) Q, integer IQ, integer JQ, integer, dimension( * ) DESCQ, double precision RHO, double precision, dimension( * ) WORK, integer, dimension( * ) IWORK, integer INFO)"

.PP
Definition at line 3 of file pdlaed1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
