.TH "SRC/pdlarfg.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdlarfg.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlarfg\fP (N, ALPHA, IAX, JAX, X, IX, JX, DESCX, INCX, TAU)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlarfg (integer N, double precision ALPHA, integer IAX, integer JAX, double precision, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer INCX, double precision, dimension( * ) TAU)"

.PP
Definition at line 3 of file pdlarfg\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
