.TH "TOOLS/pdlawrite.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pdlawrite.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlawrite\fP (FILNAM, M, N, A, IA, JA, DESCA, IRWRIT, ICWRIT, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlawrite (character*(*) FILNAM, integer M, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer IRWRIT, integer ICWRIT, double precision, dimension( * ) WORK)"

.PP
Definition at line 3 of file pdlawrite\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
