.TH "SRC/pdlaconsb.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdlaconsb.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdlaconsb\fP (A, DESCA, I, L, M, H44, H33, H43H34, BUF, LWORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdlaconsb (double precision, dimension( * ) A, integer, dimension( * ) DESCA, integer I, integer L, integer M, double precision H44, double precision H33, double precision H43H34, double precision, dimension( * ) BUF, integer LWORK)"

.PP
Definition at line 3 of file pdlaconsb\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
