.TH "SRC/pdpotrf.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdpotrf.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdpotrf\fP (UPLO, N, A, IA, JA, DESCA, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdpotrf (character UPLO, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer INFO)"

.PP
Definition at line 2 of file pdpotrf\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
