.TH "TESTING/LIN/pdqrdriver.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pdqrdriver.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpdqrdriver\fP"
.br
.ti -1c
.RI "subroutine \fBpdqppiv\fP (M, N, A, IA, JA, DESCA, IPIV)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdqppiv (integer M, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( * ) IPIV)"

.PP
Definition at line 868 of file pdqrdriver\&.f\&.
.SS "program pdqrdriver ()"

.PP
Definition at line 1 of file pdqrdriver\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
