.TH "TESTING/EIG/pdseprtst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pdseprtst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdseprtst\fP (DESCA, UPLO, N, MATTYPE, SUBTESTS, THRESH, ORDER, ABSTOL, ISEED, A, COPYA, Z, LDA, WIN, WNEW, IFAIL, ICLUSTR, GAP, IPREPAD, IPOSTPAD, WORK, LWORK, IWORK, LIWORK, HETERO, NOUT, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdseprtst (integer, dimension( * ) DESCA, character UPLO, integer N, integer MATTYPE, character SUBTESTS, double precision THRESH, integer ORDER, double precision ABSTOL, integer, dimension( 4 ) ISEED, double precision, dimension( lda, * ) A, double precision, dimension( lda, * ) COPYA, double precision, dimension( lda, * ) Z, integer LDA, double precision, dimension( * ) WIN, double precision, dimension( * ) WNEW, integer, dimension( * ) IFAIL, integer, dimension( * ) ICLUSTR, double precision, dimension( * ) GAP, integer IPREPAD, integer IPOSTPAD, double precision, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer LIWORK, character HETERO, integer NOUT, integer INFO)"

.PP
Definition at line 6 of file pdseprtst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
