.TH "SRC/pdsyntrd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pdsyntrd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdsyntrd\fP (UPLO, N, A, IA, JA, DESCA, D, E, TAU, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pdsyntrd (character UPLO, integer N, double precision, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision, dimension( * ) D, double precision, dimension( * ) E, double precision, dimension( * ) TAU, double precision, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pdsyntrd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
