.TH "TOOLS/pdtreecomb.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pdtreecomb.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpdtreecomb\fP (ICTXT, SCOPE, N, MINE, RDEST0, CDEST0, SUBPTR)"
.br
.ti -1c
.RI "subroutine \fBdcombamax\fP (V1, V2)"
.br
.ti -1c
.RI "subroutine \fBdcombssq\fP (V1, V2)"
.br
.ti -1c
.RI "subroutine \fBdcombnrm2\fP (X, Y)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dcombamax (double precision, dimension( 2 ) V1, double precision, dimension( 2 ) V2)"

.PP
Definition at line 213 of file pdtreecomb\&.f\&.
.SS "subroutine dcombnrm2 (double precision X, double precision Y)"

.PP
Definition at line 307 of file pdtreecomb\&.f\&.
.SS "subroutine dcombssq (double precision, dimension( 2 ) V1, double precision, dimension( 2 ) V2)"

.PP
Definition at line 259 of file pdtreecomb\&.f\&.
.SS "subroutine pdtreecomb (integer ICTXT, character SCOPE, integer N, double precision, dimension( * ) MINE, integer RDEST0, integer CDEST0, external SUBPTR)"

.PP
Definition at line 3 of file pdtreecomb\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
