.TH "TOOLS/pilaprnt.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pilaprnt.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpilaprnt\fP (M, N, A, IA, JA, DESCA, IRPRNT, ICPRNT, CMATNM, NOUT, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pilaprnt (integer M, integer N, integer, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer IRPRNT, integer ICPRNT, character*(*) CMATNM, integer NOUT, integer, dimension( * ) WORK)"

.PP
Definition at line 3 of file pilaprnt\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
