.TH "SRC/pjlaenv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pjlaenv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function \fBpjlaenv\fP (ICTXT, ISPEC, NAME, OPTS, N1, N2, N3, N4)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function pjlaenv (integer ICTXT, integer ISPEC, character*( * ) NAME, character*( * ) OPTS, integer N1, integer N2, integer N3, integer N4)"

.PP
Definition at line 3 of file pjlaenv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
