.TH "TESTING/LIN/psbmatgen.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/psbmatgen.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpsbmatgen\fP (ICTXT, AFORM, AFORM2, BWL, BWU, N, MB, NB, A, LDA, IAROW, IACOL, ISEED, MYROW, MYCOL, NPROW, NPCOL)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine psbmatgen (integer ICTXT, character*1 AFORM, character*1 AFORM2, integer BWL, integer BWU, integer N, integer MB, integer NB, real, dimension( lda, * ) A, integer LDA, integer IAROW, integer IACOL, integer ISEED, integer MYROW, integer MYCOL, integer NPROW, integer NPCOL)"

.PP
Definition at line 5 of file psbmatgen\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
