.TH "TOOLS/pselset2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/pselset2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpselset2\fP (ALPHA, A, IA, JA, DESCA, BETA)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pselset2 (real ALPHA, real, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real BETA)"

.PP
Definition at line 2 of file pselset2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
