.TH "SRC/psgeqr2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/psgeqr2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpsgeqr2\fP (M, N, A, IA, JA, DESCA, TAU, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine psgeqr2 (integer M, integer N, real, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) TAU, real, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file psgeqr2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
