.TH "TESTING/EIG/pshrddriver.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pshrddriver.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpshrddriver\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program pshrddriver ()"

.PP
Definition at line 1 of file pshrddriver\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
