.TH "SRC/pslarf.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pslarf.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpslarf\fP (SIDE, M, N, V, IV, JV, DESCV, INCV, TAU, C, IC, JC, DESCC, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pslarf (character SIDE, integer M, integer N, real, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, integer INCV, real, dimension( * ) TAU, real, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, real, dimension( * ) WORK)"

.PP
Definition at line 3 of file pslarf\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
