.TH "SRC/pslaqr1.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pslaqr1.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "recursive subroutine \fBpslaqr1\fP (WANTT, WANTZ, N, ILO, IHI, A, DESCA, WR, WI, ILOZ, IHIZ, Z, DESCZ, WORK, LWORK, IWORK, ILWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "recursive subroutine pslaqr1 (logical WANTT, logical WANTZ, integer N, integer ILO, integer IHI, real, dimension( * ) A, integer, dimension( * ) DESCA, real, dimension( * ) WR, real, dimension( * ) WI, integer ILOZ, integer IHIZ, real, dimension( * ) Z, integer, dimension( * ) DESCZ, real, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer ILWORK, integer INFO)"

.PP
Definition at line 5 of file pslaqr1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
