.TH "SRC/pslaiect.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pslaiect.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pxsyevx\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBproto\fP(x)   ()"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpslasnbt_\fP (int *ieflag)"
.br
.ti -1c
.RI "void \fBpslaiect_\fP (float *sigma, int *n, float *d, int *count)"
.br
.ti -1c
.RI "void \fBpslachkieee_\fP (int *isieee, float *rmax, float *rmin)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define proto(x)   ()"

.PP
Definition at line 19 of file pslaiect\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void pslachkieee_ (int * isieee, float * rmax, float * rmin)"

.PP
Definition at line 144 of file pslaiect\&.c\&.
.SS "void pslaiect_ (float * sigma, int * n, float * d, int * count)"

.PP
Definition at line 79 of file pslaiect\&.c\&.
.SS "void pslasnbt_ (int * ieflag)"

.PP
Definition at line 22 of file pslaiect\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
