.TH "SRC/pslaed0.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pslaed0.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpslaed0\fP (N, D, E, Q, IQ, JQ, DESCQ, WORK, IWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pslaed0 (integer N, real, dimension( * ) D, real, dimension( * ) E, real, dimension( * ) Q, integer IQ, integer JQ, integer, dimension( * ) DESCQ, real, dimension( * ) WORK, integer, dimension( * ) IWORK, integer INFO)"

.PP
Definition at line 2 of file pslaed0\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
