.TH "TOOLS/psmatadd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/psmatadd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpsmatadd\fP (M, N, ALPHA, A, IA, JA, DESCA, BETA, C, IC, JC, DESCC)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine psmatadd (integer M, integer N, real ALPHA, real, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real BETA, real, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC)"

.PP
Definition at line 3 of file psmatadd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
