.TH "SRC/pspttrs.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pspttrs.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpspttrs\fP (N, NRHS, D, E, JA, DESCA, B, IB, DESCB, AF, LAF, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pspttrs (integer N, integer NRHS, real, dimension( * ) D, real, dimension( * ) E, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) B, integer IB, integer, dimension( * ) DESCB, real, dimension( * ) AF, integer LAF, real, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pspttrs\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
