.TH "TESTING/EIG/pssqpsubtst.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pssqpsubtst.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpssqpsubtst\fP (WKNOWN, JOBZ, UPLO, N, THRESH, ABSTOL, A, COPYA, Z, IA, JA, DESCA, WIN, WNEW, IPREPAD, IPOSTPAD, WORK, LWORK, LWORK1, RESULT, TSTNRM, QTQNRM, NOUT)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pssqpsubtst (logical WKNOWN, character JOBZ, character UPLO, integer N, real THRESH, real ABSTOL, real, dimension( * ) A, real, dimension( * ) COPYA, real, dimension( * ) Z, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) WIN, real, dimension( * ) WNEW, integer IPREPAD, integer IPOSTPAD, real, dimension( * ) WORK, integer LWORK, integer LWORK1, integer RESULT, real TSTNRM, real QTQNRM, integer NOUT)"

.PP
Definition at line 7 of file pssqpsubtst\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
