.TH "TESTING/EIG/pssvdcmp.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pssvdcmp.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpssvdcmp\fP (M, N, JOBTYPE, S, SC, U, UC, IU, JU, DESCU, VT, VTC, IVT, JVT, DESCVT, THRESH, RESULT, DELTA, WORK, LWORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pssvdcmp (integer M, integer N, integer JOBTYPE, real, dimension( * ) S, real, dimension( * ) SC, real, dimension( * ) U, real, dimension( * ) UC, integer IU, integer JU, integer, dimension( * ) DESCU, real, dimension( * ) VT, real, dimension( * ) VTC, integer IVT, integer JVT, integer, dimension( * ) DESCVT, real THRESH, integer, dimension( * ) RESULT, real DELTA, real, dimension( * ) WORK, integer LWORK)"

.PP
Definition at line 4 of file pssvdcmp\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
