.TH "SRC/pssygvx.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pssygvx.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpssygvx\fP (IBTYPE, JOBZ, RANGE, UPLO, N, A, IA, JA, DESCA, B, IB, JB, DESCB, VL, VU, IL, IU, ABSTOL, M, NZ, W, ORFAC, Z, IZ, JZ, DESCZ, WORK, LWORK, IWORK, LIWORK, IFAIL, ICLUSTR, GAP, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pssygvx (integer IBTYPE, character JOBZ, character RANGE, character UPLO, integer N, real, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, real, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB, real VL, real VU, integer IL, integer IU, real ABSTOL, integer M, integer NZ, real, dimension( * ) W, real ORFAC, real, dimension( * ) Z, integer IZ, integer JZ, integer, dimension( * ) DESCZ, real, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer LIWORK, integer, dimension( * ) IFAIL, integer, dimension( * ) ICLUSTR, real, dimension( * ) GAP, integer INFO)"

.PP
Definition at line 6 of file pssygvx\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
