.TH "SRC/pstrord.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pstrord.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpstrord\fP (COMPQ, SELECT, PARA, N, T, IT, JT, DESCT, Q, IQ, JQ, DESCQ, WR, WI, M, WORK, LWORK, IWORK, LIWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pstrord (character COMPQ, integer, dimension( * ) SELECT, integer, dimension( 6 ) PARA, integer N, real, dimension( * ) T, integer IT, integer JT, integer, dimension( * ) DESCT, real, dimension( * ) Q, integer IQ, integer JQ, integer, dimension( * ) DESCQ, real, dimension( * ) WR, real, dimension( * ) WI, integer M, real, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer LIWORK, integer INFO)"

.PP
Definition at line 4 of file pstrord\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
