.TH "PBLAS/SRC/pstrmm_.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/pstrmm_.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pblas\&.h'\fP
.br
\fC#include 'PBpblas\&.h'\fP
.br
\fC#include 'PBtools\&.h'\fP
.br
\fC#include 'PBblacs\&.h'\fP
.br
\fC#include 'PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpstrmm_\fP (\fBF_CHAR_T\fP SIDE, \fBF_CHAR_T\fP UPLO, \fBF_CHAR_T\fP TRANS, \fBF_CHAR_T\fP DIAG, int *M, int *N, float *ALPHA, float *A, int *IA, int *JA, int *DESCA, float *B, int *IB, int *JB, int *DESCB)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pstrmm_ (\fBF_CHAR_T\fP SIDE, \fBF_CHAR_T\fP UPLO, \fBF_CHAR_T\fP TRANS, \fBF_CHAR_T\fP DIAG, int * M, int * N, float          * ALPHA, float          * A, int            * IA, int * JA, int            * DESCA, float * B, int * IB, int * JB, int * DESCB)"

.PP
Definition at line 25 of file pstrmm_\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
