.TH "SRC/pxsyevx.h" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pxsyevx.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADD_\fP   0"
.br
.ti -1c
.RI "#define \fBNOCHANGE\fP   1"
.br
.ti -1c
.RI "#define \fBUPCASE\fP   2"
.br
.ti -1c
.RI "#define \fBC_CALL\fP   3"
.br
.ti -1c
.RI "#define \fBF77_CALL_C\fP   \fBADD_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADD_   0"

.PP
Definition at line 13 of file pxsyevx\&.h\&.
.SS "#define C_CALL   3"

.PP
Definition at line 16 of file pxsyevx\&.h\&.
.SS "#define F77_CALL_C   \fBADD_\fP"

.PP
Definition at line 31 of file pxsyevx\&.h\&.
.SS "#define NOCHANGE   1"

.PP
Definition at line 14 of file pxsyevx\&.h\&.
.SS "#define UPCASE   2"

.PP
Definition at line 15 of file pxsyevx\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
