.TH "SRC/pzdttrs.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzdttrs.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzdttrs\fP (TRANS, N, NRHS, DL, D, DU, JA, DESCA, B, IB, DESCB, AF, LAF, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzdttrs (character TRANS, integer N, integer NRHS, \fBcomplex\fP*16, dimension( * ) DL, \fBcomplex\fP*16, dimension( * ) D, \fBcomplex\fP*16, dimension( * ) DU, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP*16, dimension( * ) B, integer IB, integer, dimension( * ) DESCB, \fBcomplex\fP*16, dimension( * ) AF, integer LAF, \fBcomplex\fP*16, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pzdttrs\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
