.TH "PBLAS/SRC/pzgeadd_.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/pzgeadd_.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pblas\&.h'\fP
.br
\fC#include 'PBpblas\&.h'\fP
.br
\fC#include 'PBtools\&.h'\fP
.br
\fC#include 'PBblacs\&.h'\fP
.br
\fC#include 'PBblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpzgeadd_\fP (\fBF_CHAR_T\fP TRANS, int *M, int *N, double *ALPHA, double *A, int *IA, int *JA, int *DESCA, double *BETA, double *C, int *IC, int *JC, int *DESCC)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pzgeadd_ (\fBF_CHAR_T\fP TRANS, int * M, int * N, double         * ALPHA, double         * A, int            * IA, int * JA, int            * DESCA, double * BETA, double * C, int * IC, int * JC, int * DESCC)"

.PP
Definition at line 26 of file pzgeadd_\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
