.TH "SRC/pzlacon.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlacon.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlacon\fP (N, V, IV, JV, DESCV, X, IX, JX, DESCX, EST, KASE)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlacon (integer N, \fBcomplex\fP*16, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, \fBcomplex\fP*16, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, double precision EST, integer KASE)"

.PP
Definition at line 3 of file pzlacon\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
