.TH "SRC/pzlahrd.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlahrd.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlahrd\fP (N, K, NB, A, IA, JA, DESCA, TAU, T, Y, IY, JY, DESCY, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlahrd (integer N, integer K, integer NB, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP*16, dimension( * ) TAU, \fBcomplex\fP*16, dimension( * ) T, \fBcomplex\fP*16, dimension( * ) Y, integer IY, integer JY, integer, dimension( * ) DESCY, \fBcomplex\fP*16, dimension( * ) WORK)"

.PP
Definition at line 3 of file pzlahrd\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
