.TH "SRC/pzlarft.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlarft.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlarft\fP (DIRECT, STOREV, N, K, V, IV, JV, DESCV, TAU, T, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlarft (character DIRECT, character STOREV, integer N, integer K, \fBcomplex\fP*16, dimension( * ) V, integer IV, integer JV, integer, dimension( * ) DESCV, \fBcomplex\fP*16, dimension( * ) TAU, \fBcomplex\fP*16, dimension( * ) T, \fBcomplex\fP*16, dimension( * ) WORK)"

.PP
Definition at line 3 of file pzlarft\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
