.TH "TESTING/EIG/pzlagsy.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pzlagsy.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlaghe\fP (N, K, D, A, IA, JA, DESCA, ISEED, ORDER, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlaghe (integer N, integer K, double precision, dimension( * ) D, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( 4 ) ISEED, integer ORDER, \fBcomplex\fP*16, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 5 of file pzlagsy\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
