.TH "SRC/pzlasmsub.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlasmsub.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlasmsub\fP (A, DESCA, I, L, K, SMLNUM, BUF, LWORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlasmsub (\fBcomplex\fP*16, dimension( * ) A, integer, dimension( * ) DESCA, integer I, integer L, integer K, double precision SMLNUM, \fBcomplex\fP*16, dimension( * ) BUF, integer LWORK)"

.PP
Definition at line 2 of file pzlasmsub\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
