.TH "SRC/pzlacpy.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlacpy.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlacpy\fP (UPLO, M, N, A, IA, JA, DESCA, B, IB, JB, DESCB)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlacpy (character UPLO, integer M, integer N, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP*16, dimension( * ) B, integer IB, integer JB, integer, dimension( * ) DESCB)"

.PP
Definition at line 3 of file pzlacpy\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
