.TH "SRC/pzlatra.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlatra.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "\fBcomplex\fP *16 function \fBpzlatra\fP (N, A, IA, JA, DESCA)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "\fBcomplex\fP*16 function pzlatra (integer N, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA)"

.PP
Definition at line 2 of file pzlatra\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
