.TH "SRC/pzlahqr.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzlahqr.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlahqr\fP (WANTT, WANTZ, N, ILO, IHI, A, DESCA, W, ILOZ, IHIZ, Z, DESCZ, WORK, LWORK, IWORK, ILWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlahqr (logical WANTT, logical WANTZ, integer N, integer ILO, integer IHI, \fBcomplex\fP*16, dimension( * ) A, integer, dimension( * ) DESCA, \fBcomplex\fP*16, dimension( * ) W, integer ILOZ, integer IHIZ, \fBcomplex\fP*16, dimension( * ) Z, integer, dimension( * ) DESCZ, \fBcomplex\fP*16, dimension( * ) WORK, integer LWORK, integer, dimension( * ) IWORK, integer ILWORK, integer INFO)"

.PP
Definition at line 4 of file pzlahqr\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
