.TH "TESTING/LIN/pzlaschk.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pzlaschk.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzlaschk\fP (\fBSYMM\fP, DIAG, N, NRHS, X, IX, JX, DESCX, IASEED, IA, JA, DESCA, IBSEED, ANORM, RESID, WORK)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzlaschk (character SYMM, character DIAG, integer N, integer NRHS, \fBcomplex\fP*16, dimension( * ) X, integer IX, integer JX, integer, dimension( * ) DESCX, integer IASEED, integer IA, integer JA, integer, dimension( * ) DESCA, integer IBSEED, double precision ANORM, double precision RESID, \fBcomplex\fP*16, dimension( * ) WORK)"

.PP
Definition at line 4 of file pzlaschk\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
