.TH "TESTING/LIN/pzqrdriver.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/LIN/pzqrdriver.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBpzqrdriver\fP"
.br
.ti -1c
.RI "subroutine \fBpzqppiv\fP (M, N, A, IA, JA, DESCA, IPIV)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzqppiv (integer M, integer N, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, integer, dimension( * ) IPIV)"

.PP
Definition at line 889 of file pzqrdriver\&.f\&.
.SS "program pzqrdriver ()"

.PP
Definition at line 1 of file pzqrdriver\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
