.TH "SRC/pzrot.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzrot.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pblas\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpzrot_\fP (int *n, X, int *ix, int *jx, desc_X, int *incx, Y, int *iy, int *jy, desc_Y, int *incy, double *c, \fBcomplex16\fP *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void pzrot_ (int * n, X, int * ix, int * jx, desc_X, int         * incx, Y, int * iy, int * jy, desc_Y, int * incy, double      * c, \fBcomplex16\fP   * s)"

.PP
Definition at line 13 of file pzrot\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
