.TH "TESTING/EIG/pzsepqtq.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pzsepqtq.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzsepqtq\fP (MS, NV, THRESH, Q, IQ, JQ, DESCQ, C, IC, JC, DESCC, PROCDIST, ICLUSTR, GAP, WORK, LWORK, QTQNRM, INFO, RES)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzsepqtq (integer MS, integer NV, double precision THRESH, \fBcomplex\fP*16, dimension( * ) Q, integer IQ, integer JQ, integer, dimension( * ) DESCQ, \fBcomplex\fP*16, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, integer, dimension( * ) PROCDIST, integer, dimension( * ) ICLUSTR, double precision, dimension( * ) GAP, double precision, dimension( * ) WORK, integer LWORK, double precision QTQNRM, integer INFO, integer RES)"

.PP
Definition at line 6 of file pzsepqtq\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
