.TH "TESTING/EIG/pzsepchk.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TESTING/EIG/pzsepchk.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzsepchk\fP (MS, NV, A, IA, JA, DESCA, EPSNORMA, THRESH, Q, IQ, JQ, DESCQ, C, IC, JC, DESCC, W, WORK, LWORK, TSTNRM, RESULT)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzsepchk (integer MS, integer NV, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, double precision EPSNORMA, double precision THRESH, \fBcomplex\fP*16, dimension( * ) Q, integer IQ, integer JQ, integer, dimension( * ) DESCQ, \fBcomplex\fP*16, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, double precision, dimension( * ) W, double precision, dimension( * ) WORK, integer LWORK, double precision TSTNRM, integer RESULT)"

.PP
Definition at line 6 of file pzsepchk\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
