.TH "SRC/pzunm2l.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/pzunm2l.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpzunm2l\fP (SIDE, TRANS, M, N, K, A, IA, JA, DESCA, TAU, C, IC, JC, DESCC, WORK, LWORK, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine pzunm2l (character SIDE, character TRANS, integer M, integer N, integer K, \fBcomplex\fP*16, dimension( * ) A, integer IA, integer JA, integer, dimension( * ) DESCA, \fBcomplex\fP*16, dimension( * ) TAU, \fBcomplex\fP*16, dimension( * ) C, integer IC, integer JC, integer, dimension( * ) DESCC, \fBcomplex\fP*16, dimension( * ) WORK, integer LWORK, integer INFO)"

.PP
Definition at line 3 of file pzunm2l\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
