.TH "PBLAS/SRC/PTZBLAS/sagemv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/sagemv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBsagemv\fP (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine sagemv (character*1 TRANS, integer M, integer N, real ALPHA, real, dimension( lda, * ) A, integer LDA, real, dimension( * ) X, integer INCX, real BETA, real, dimension( * ) Y, integer INCY)"

.PP
Definition at line 3 of file sagemv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
