.TH "SCOMPLEX" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCOMPLEX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bdef\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file Bdef\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float SCOMPLEX::i"

.PP
Definition at line 38 of file Bdef\&.h\&.
.SS "float SCOMPLEX::r"

.PP
Definition at line 38 of file Bdef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
