.TH "PBLAS/TESTING/slamch.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/TESTING/slamch.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real function \fBslamch\fP (CMACH)"
.br
.ti -1c
.RI "subroutine \fBslamc1\fP (BETA, T, RND, IEEE1)"
.br
.ti -1c
.RI "subroutine \fBslamc2\fP (BETA, T, RND, EPS, EMIN, RMIN, EMAX, RMAX)"
.br
.ti -1c
.RI "real function \fBslamc3\fP (A, B)"
.br
.ti -1c
.RI "subroutine \fBslamc4\fP (EMIN, START, BASE)"
.br
.ti -1c
.RI "subroutine \fBslamc5\fP (BETA, P, EMIN, IEEE, EMAX, RMAX)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slamc1 (integer BETA, integer T, logical RND, logical IEEE1)"

.PP
Definition at line 132 of file slamch\&.f\&.
.SS "subroutine slamc2 (integer BETA, integer T, logical RND, real EPS, integer EMIN, real RMIN, integer EMAX, real RMAX)"

.PP
Definition at line 319 of file slamch\&.f\&.
.SS "real function slamc3 (real A, real B)"

.PP
Definition at line 578 of file slamch\&.f\&.
.SS "subroutine slamc4 (integer EMIN, real START, integer BASE)"

.PP
Definition at line 616 of file slamch\&.f\&.
.SS "subroutine slamc5 (integer BETA, integer P, integer EMIN, logical IEEE, integer EMAX, real RMAX)"

.PP
Definition at line 700 of file slamch\&.f\&.
.SS "real function slamch (character CMACH)"

.PP
Definition at line 2 of file slamch\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
