.TH "SRC/slarrb2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/slarrb2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslarrb2\fP (N, D, LLD, IFIRST, ILAST, RTOL1, RTOL2, OFFSET, W, WGAP, WERR, WORK, IWORK, PIVMIN, LGPVMN, LGSPDM, TWIST, INFO)"
.br
.ti -1c
.RI "integer function \fBslaneg2\fP (N, D, LLD, SIGMA, PIVMIN, R)"
.br
.ti -1c
.RI "integer function \fBslaneg2a\fP (N, DLLD, SIGMA, PIVMIN, R)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "integer function slaneg2 (integer N, real, dimension( * ) D, real, dimension( * ) LLD, real SIGMA, real PIVMIN, integer R)"

.PP
Definition at line 337 of file slarrb2\&.f\&.
.SS "integer function slaneg2a (integer N, real, dimension( * ) DLLD, real SIGMA, real PIVMIN, integer R)"

.PP
Definition at line 491 of file slarrb2\&.f\&.
.SS "subroutine slarrb2 (integer N, real, dimension( * ) D, real, dimension( * ) LLD, integer IFIRST, integer ILAST, real RTOL1, real RTOL2, integer OFFSET, real, dimension( * ) W, real, dimension( * ) WGAP, real, dimension( * ) WERR, real, dimension( * ) WORK, integer, dimension( * ) IWORK, real PIVMIN, real LGPVMN, real LGSPDM, integer TWIST, integer INFO)"

.PP
Definition at line 4 of file slarrb2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
