.TH "TOOLS/LAPACK/slaran.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/LAPACK/slaran.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "real function \fBslaran\fP (ISEED)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "real function slaran (integer, dimension( 4 ) ISEED)"

.PP
Definition at line 2 of file slaran\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
