.TH "SRC/slasrt2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/slasrt2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslasrt2\fP (ID, N, D, KEY, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slasrt2 (character ID, integer N, real, dimension( * ) D, integer, dimension( * ) KEY, integer INFO)"

.PP
Definition at line 4 of file slasrt2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
