.TH "TOOLS/sltimer.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/sltimer.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslboot\fP ()"
.br
.ti -1c
.RI "subroutine \fBsltimer\fP (I)"
.br
.ti -1c
.RI "subroutine \fBslenable\fP ()"
.br
.ti -1c
.RI "subroutine \fBsldisable\fP ()"
.br
.ti -1c
.RI "double precision function \fBslinquire\fP (TIMETYPE, I)"
.br
.ti -1c
.RI "subroutine \fBslcombine\fP (ICTXT, SCOPE, OP, TIMETYPE, N, IBEG, TIMES)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slboot ()"

.PP
Definition at line 2 of file sltimer\&.f\&.
.SS "subroutine slcombine (integer ICTXT, character SCOPE, character OP, character TIMETYPE, integer N, integer IBEG, double precision, dimension( n ) TIMES)"

.PP
Definition at line 267 of file sltimer\&.f\&.
.SS "subroutine sldisable ()"

.PP
Definition at line 155 of file sltimer\&.f\&.
.SS "subroutine slenable ()"

.PP
Definition at line 123 of file sltimer\&.f\&.
.SS "double precision function slinquire (character*1 TIMETYPE, integer I)"

.PP
Definition at line 189 of file sltimer\&.f\&.
.SS "subroutine sltimer (integer I)"

.PP
Definition at line 47 of file sltimer\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
