.TH "BLACS/INSTALL/tc_cCsameF77.c" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLACS/INSTALL/tc_cCsameF77.c
.SH SYNOPSIS
.br
.PP
\fC#include <mpi\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCcommcheck\fP (int F77World, int f77comm)"
.br
.ti -1c
.RI "int \fBCCOMMCHECK\fP (int *F77World, int *f77comm)"
.br
.ti -1c
.RI "int \fBccommcheck_\fP (int *F77World, int *f77comm)"
.br
.ti -1c
.RI "int \fBccommcheck\fP (int *F77World, int *f77comm)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int CCOMMCHECK (int * F77World, int * f77comm)"

.PP
Definition at line 27 of file tc_cCsameF77\&.c\&.
.SS "int ccommcheck (int * F77World, int * f77comm)"

.PP
Definition at line 35 of file tc_cCsameF77\&.c\&.
.SS "int Ccommcheck (int F77World, int f77comm)"

.PP
Definition at line 3 of file tc_cCsameF77\&.c\&.
.SS "int ccommcheck_ (int * F77World, int * f77comm)"

.PP
Definition at line 31 of file tc_cCsameF77\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
