.TH "SRC/zdttrsv.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/zdttrsv.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzdttrsv\fP (UPLO, TRANS, N, NRHS, DL, D, DU, B, LDB, INFO)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zdttrsv (character UPLO, character TRANS, integer N, integer NRHS, \fBcomplex\fP*16, dimension( * ) DL, \fBcomplex\fP*16, dimension( * ) D, \fBcomplex\fP*16, dimension( * ) DU, \fBcomplex\fP*16, dimension( ldb, * ) B, integer LDB, integer INFO)"

.PP
Definition at line 3 of file zdttrsv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
