.TH "SRC/zlanv2.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRC/zlanv2.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzlanv2\fP (A, B, C, D, RT1, RT2, CS, SN)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zlanv2 (\fBcomplex\fP*16 A, \fBcomplex\fP*16 B, \fBcomplex\fP*16 C, \fBcomplex\fP*16 D, \fBcomplex\fP*16 RT1, \fBcomplex\fP*16 RT2, double precision CS, \fBcomplex\fP*16 SN)"

.PP
Definition at line 2 of file zlanv2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
