.TH "TOOLS/LAPACK/zlarot.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TOOLS/LAPACK/zlarot.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzlarot\fP (LROWS, LLEFT, LRIGHT, NL, C, S, A, LDA, XLEFT, XRIGHT)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zlarot (logical LROWS, logical LLEFT, logical LRIGHT, integer NL, \fBcomplex\fP*16 C, \fBcomplex\fP*16 S, \fBcomplex\fP*16, dimension( * ) A, integer LDA, \fBcomplex\fP*16 XLEFT, \fBcomplex\fP*16 XRIGHT)"

.PP
Definition at line 3 of file zlarot\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
