.TH "PBLAS/SRC/PTZBLAS/ztzscal.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/ztzscal.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBztzscal\fP (UPLO, M, N, IOFFD, ALPHA, A, LDA)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ztzscal (character*1 UPLO, integer M, integer N, integer IOFFD, \fBcomplex\fP*16 ALPHA, \fBcomplex\fP*16, dimension( lda, * ) A, integer LDA)"

.PP
Definition at line 2 of file ztzscal\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
