.TH "PBLAS/SRC/PTZBLAS/zvvdotu.f" 3 "Sat Nov 16 2019" "Version 2.1" "ScaLAPACK 2.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PBLAS/SRC/PTZBLAS/zvvdotu.f
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzvvdotu\fP (N, DOT, X, INCX, Y, INCY)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zvvdotu (integer N, \fBcomplex\fP*16 DOT, \fBcomplex\fP*16, dimension( * ) X, integer INCX, \fBcomplex\fP*16, dimension( * ) Y, integer INCY)"

.PP
Definition at line 2 of file zvvdotu\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ScaLAPACK 2\&.1 from the source code\&.
